# -*- coding: utf-8 -*-
"""GANTrain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9iP8x9vFVS6j6zKmyd4W51VqLpuP3vD
"""

import torch
import torch.nn as nn
import torch.optim as optim
import json
import numpy as np
import os
import glob

# Generator network using convolutional layers with dynamic sizing
class ConvGenerator(nn.Module):
    def __init__(self, latent_dim, grid_size, num_colors):
        super(ConvGenerator, self).__init__()
        self.latent_dim = latent_dim
        self.grid_size = grid_size
        self.num_colors = num_colors

        # Calculate a suitable starting size for transposed convolutions
        start_h = 4
        start_w = 4

        self.fc = nn.Linear(latent_dim, 64 * start_h * start_w)

        self.main = nn.Sequential(
            # First transposed convolution layer (upscaling to 8x8)
            nn.ConvTranspose2d(64, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(True),

            # Second transposed convolution layer (upscaling to 16x16)
            nn.ConvTranspose2d(64, 32, 4, 2, 1, bias=False),
            nn.BatchNorm2d(32),
            nn.ReLU(True),

            # Final transposed convolution layer
            nn.ConvTranspose2d(32, 1, 4, 2, 1, bias=False),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.fc(x)
        x = x.view(-1, 64, 4, 4)
        x = self.main(x)

        # Use interpolation to resize the output to the exact target size
        x = nn.functional.interpolate(x, size=self.grid_size, mode='bilinear', align_corners=False)
        return x

# Updated Discriminator network with Adaptive Pooling to handle arbitrary input sizes
class ConvDiscriminator(nn.Module):
    def __init__(self, grid_size):
        super(ConvDiscriminator, self).__init__()
        self.grid_size = grid_size

        # Adaptive pooling to normalize all input grids to a fixed size (e.g., 16x16)
        self.adaptive_pool = nn.AdaptiveAvgPool2d((16, 16))

        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 32, 4, 2, 1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(32, 64, 4, 2, 1, bias=False),
            nn.BatchNorm2d(64),
            nn.LeakyReLU(0.2, inplace=True),

            nn.Conv2d(64, 128, 4, 2, 1, bias=False),
            nn.BatchNorm2d(128),
            nn.LeakyReLU(0.2, inplace=True)
        )

        # Dynamically calculate the size for the linear layer based on the fixed pooled size
        with torch.no_grad():
            dummy_input = torch.zeros(1, 1, 16, 16)
            x = self.conv_layers(dummy_input)
            flattened_size = x.numel()

        self.linear_layer = nn.Sequential(
            nn.Flatten(),
            nn.Linear(flattened_size, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        # Add a channel dimension if it's missing
        if len(x.shape) == 3:
            x = x.unsqueeze(1)

        # Resize input grids to a fixed size using adaptive pooling
        x = self.adaptive_pool(x)

        x = self.conv_layers(x)
        return self.linear_layer(x)

# Linear-based Generator for small grids
class LinearGenerator(nn.Module):
    def __init__(self, latent_dim, grid_size, num_colors):
        super(LinearGenerator, self).__init__()
        self.latent_dim = latent_dim
        self.grid_size = grid_size
        self.output_size = grid_size[0] * grid_size[1]

        self.main = nn.Sequential(
            nn.Linear(latent_dim, self.output_size),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.main(x)
        return x.view(-1, 1, self.grid_size[0], self.grid_size[1])

# Linear-based Discriminator for small grids
class LinearDiscriminator(nn.Module):
    def __init__(self, grid_size):
        super(LinearDiscriminator, self).__init__()
        self.input_size = grid_size[0] * grid_size[1]

        self.main = nn.Sequential(
            nn.Linear(self.input_size, 128),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        x = x.view(-1, self.input_size)
        return self.main(x)


def load_and_group_data(file_path="/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/datasets/training_augmented_dataset.json"):
    """
    Loads the dataset and groups grids by their size, including any previously generated datasets.
    Returns a dictionary mapping grid size to a list of grids.
    """
    grouped_data = {}

    # Load original training data
    try:
        with open(file_path, 'r') as f:
            data = json.load(f)
            for example in data:
                if 'output' in example and isinstance(example['output'], list):
                    output_grid = np.array(example['output'])
                    grid_shape = output_grid.shape
                    if grid_shape not in grouped_data:
                        grouped_data[grid_shape] = []
                    grouped_data[grid_shape].append(output_grid)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Error loading original data: {e}")

    # Find and load any previously generated datasets
    generated_files = glob.glob("generated_dcgan_dataset_*.json")
    for gen_file in generated_files:
        try:
            with open(gen_file, 'r') as f:
                gen_data = json.load(f)
                if gen_data:
                    # Infer grid size from the first example
                    grid_shape = np.array(gen_data[0]).shape
                    if grid_shape not in grouped_data:
                        grouped_data[grid_shape] = []

                    for grid in gen_data:
                        grouped_data[grid_shape].append(np.array(grid))
                    print(f"Loaded {len(gen_data)} examples from {gen_file}")
        except (FileNotFoundError, json.JSONDecodeError) as e:
            print(f"Error loading generated data from {gen_file}: {e}")

    return grouped_data

def train_gan_for_size(data_tensor, grid_size, latent_dim=100, num_epochs=100):
    """
    Trains a GAN for a specific grid size, choosing the model type dynamically.
    """
    num_colors = 10

    # Check if the grid is too small for the convolutional layers
    if min(grid_size) < 8:
        print(f"Using Linear models for grid size {grid_size}.")
        generator = LinearGenerator(latent_dim, grid_size, num_colors)
        discriminator = LinearDiscriminator(grid_size)
    else:
        print(f"Using Conv models for grid size {grid_size}.")
        generator = ConvGenerator(latent_dim, grid_size, num_colors)
        discriminator = ConvDiscriminator(grid_size)

    criterion = nn.BCELoss()
    d_optimizer = optim.Adam(discriminator.parameters(), lr=0.0002, betas=(0.5, 0.999))
    g_optimizer = optim.Adam(generator.parameters(), lr=0.0002, betas=(0.5, 0.999))

    for epoch in range(num_epochs):
        # --- Train the Discriminator ---
        discriminator.zero_grad()
        real_data = data_tensor[torch.randint(0, len(data_tensor), (128,))]
        real_labels = torch.full((128,), 1., dtype=torch.float)

        output = discriminator(real_data).view(-1)
        err_d_real = criterion(output, real_labels)
        err_d_real.backward()

        noise = torch.randn(128, latent_dim)
        fake_data = generator(noise)
        fake_labels = torch.full((128,), 0., dtype=torch.float)
        output = discriminator(fake_data.detach()).view(-1)
        err_d_fake = criterion(output, fake_labels)
        err_d_fake.backward()
        d_optimizer.step()

        # --- Train the Generator ---
        generator.zero_grad()
        noise = torch.randn(128, latent_dim)
        fake_data = generator(noise)
        output = discriminator(fake_data).view(-1)
        err_g = criterion(output, real_labels)
        err_g.backward()
        g_optimizer.step()

        if epoch % 10 == 0:
            print(f"Grid Size {grid_size} | Epoch [{epoch}/{num_epochs}] | D Loss: {err_d_real + err_d_fake:.4f} | G Loss: {err_g:.4f}")

    print(f"\nTraining complete for grid size {grid_size}.")
    return generator

def generate_dataset_for_size(generator, grid_size, num_examples=100):
    """
    Uses the trained generator to create a new dataset.
    """
    generator.eval()
    new_dataset = []

    print(f"\nGenerating {num_examples} new examples for grid size {grid_size}...")
    with torch.no_grad():
        for _ in range(num_examples):
            noise = torch.randn(1, generator.latent_dim)
            generated_grid = generator(noise).squeeze(0)

            generated_grid = (generated_grid + 1) / 2 * 9.5
            generated_grid = torch.round(generated_grid)
            generated_grid = torch.clamp(generated_grid, 0, 9)

            if len(generated_grid.shape) == 3:
                generated_grid = generated_grid.squeeze(0)

            new_dataset.append(generated_grid.cpu().numpy().astype(int).tolist())

    output_path = f"/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/datasets/generated_dcgan_dataset_{grid_size[0]}x{grid_size[1]}.json"

    # Append to existing file or create a new one
    existing_data = []
    if os.path.exists(output_path):
        with open(output_path, 'r') as f:
            try:
                existing_data = json.load(f)
                if not isinstance(existing_data, list):
                    existing_data = []
            except json.JSONDecodeError:
                existing_data = []

    existing_data.extend(new_dataset)

    with open(output_path, 'w') as f:
        json.dump(existing_data, f, indent=4)
    print(f"Generated dataset appended to '{output_path}'.")

if __name__ == "__main__":
    grouped_data = load_and_group_data()

    if grouped_data is not None:
        for grid_size, grids in grouped_data.items():
            data_tensor = torch.tensor(grids, dtype=torch.float32)
            data_tensor = (data_tensor / 9.5) * 2 - 1

            # Check if there's enough data to train
            if len(data_tensor) > 128:
                trained_generator = train_gan_for_size(data_tensor, grid_size, num_epochs=200)
                generate_dataset_for_size(trained_generator, grid_size, num_examples=200)
            else:
                print(f"Skipping training for grid size {grid_size} due to insufficient data ({len(data_tensor)} examples).")





