# -*- coding: utf-8 -*-
"""GAN Trainer with RL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--9Ee1V8_JxHkD_AaJX5x3G2-CPRvGO0
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile config.py
# import torch
# import pathlib
# 
# # Configuration for paths, hyperparameters, and special tokens
# CONFIG = {
#     # --- Paths ---
#     'base_data_path': pathlib.Path('/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/test1'),
#     'input_directory': 'training',  # Use 'training' for training data
#     'test_directory': 'evaluation', # Use 'evaluation' for test data
#     'output_directory': 'models/gan',
#     'rl_output_directory': 'models/rl',
#     'processed_data_file': 'processed_arc_sequences.pkl',
#     'submission_file': 'submission.json',
# 
#     # --- Data Processing / Vocabulary ---
#     'grid_size': 30, # Max grid dimension, ARC tasks vary. Common max is 30x30.
#     'max_seq_len': None, # Will be calculated dynamically after preprocessing to be max_input_len + max_output_len + 2 (START, SEP tokens)
#     'vocab_size': 11 + 3, # 0-9 for colors, + START_TOKEN, SEP_TOKEN, PAD_TOKEN
#     'START_TOKEN': 10,
#     'SEP_TOKEN': 11,
#     'PAD_TOKEN': 12, # Should be the highest index for embedding layers
# 
#     # --- GAN Hyperparameters ---
#     'gan_num_epochs': 50,
#     'gan_batch_size': 64,
#     'gan_learning_rate': 1e-4,
#     'gan_weight_decay': 1e-5,
#     'gan_gradient_clip_val': 1.0,
#     'gan_scheduler_step_size': 10,
#     'gan_scheduler_gamma': 0.8,
#     'gan_k_folds': 5, # For cross-validation
# 
#     # --- Transformer Model Architecture ---
#     'd_model': 256,
#     'nhead': 8,
#     'num_encoder_layers': 6, # For Generator and Discriminator
#     'dim_feedforward': 1024,
#     'dropout': 0.1,
# 
#     # --- Reinforcement Learning Hyperparameters ---
#     'rl_num_episodes': 5000,
#     'rl_learning_rate': 5e-5,
#     'rl_gamma': 0.99, # Discount factor for future rewards (not directly used in REINFORCE, but good to have)
#     'epsilon_start': 1.0, # Initial exploration rate
#     'epsilon_min': 0.05,  # Minimum exploration rate
#     'epsilon_decay': 0.995, # Decay rate per episode
#     'rl_checkpoint_interval': 500, # Save RL checkpoint every N episodes
#     'reward_correct_pixel': 1.0,
#     'reward_wrong_pixel': -0.5,
#     'reward_shape_mismatch': -10.0,
# }
# 
# # Ensure output directories exist
# CONFIG['output_directory'] = pathlib.Path(CONFIG['output_directory'])
# CONFIG['rl_output_directory'] = pathlib.Path(CONFIG['rl_output_directory'])
# CONFIG['output_directory'].mkdir(parents=True, exist_ok=True)
# CONFIG['rl_output_directory'].mkdir(parents=True, exist_ok=True)
# 
# # Device configuration
# CONFIG['device'] = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile dataset.py
# import torch
# from torch.utils.data import Dataset
# 
# class ARCDataset(Dataset):
#     """
#     A PyTorch Dataset for ARC sequences.
#     Each item is a preprocessed sequence of tokens representing an input-output pair.
#     """
#     def __init__(self, sequences):
#         self.sequences = sequences
# 
#     def __len__(self):
#         return len(self.sequences)
# 
#     def __getitem__(self, idx):
#         return self.sequences[idx]
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models.py
# import torch
# import torch.nn as nn
# import torch.nn.functional as F
# 
# class Generator(nn.Module):
#     """
#     The Generator network for the GAN and Policy network for RL.
#     It's a Transformer Encoder that generates output sequences based on input sequences.
#     """
#     def __init__(self, vocab_size, d_model, nhead, num_layers, dim_feedforward, dropout):
#         super(Generator, self).__init__()
#         self.embedding = nn.Embedding(vocab_size, d_model)
#         encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead,
#                                                     dim_feedforward=dim_feedforward, dropout=dropout,
#                                                     batch_first=True)
#         self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
#         self.fc_out = nn.Linear(d_model, vocab_size) # Predict token probabilities
# 
#     def forward(self, src):
#         # src shape: (batch_size, sequence_length)
#         embedded = self.embedding(src) # (batch_size, sequence_length, d_model)
#         output = self.transformer_encoder(embedded) # (batch_size, sequence_length, d_model)
#         logits = self.fc_out(output) # (batch_size, sequence_length, vocab_size)
#         return logits
# 
# class Discriminator(nn.Module):
#     """
#     The Discriminator network for the GAN.
#     It's a Transformer Encoder that classifies sequences as real or fake.
#     """
#     def __init__(self, vocab_size, d_model, nhead, num_layers, dim_feedforward, dropout):
#         super(Discriminator, self).__init__()
#         self.embedding = nn.Embedding(vocab_size, d_model)
#         encoder_layer = nn.TransformerEncoderLayer(d_model=d_model, nhead=nhead,
#                                                     dim_feedforward=dim_feedforward, dropout=dropout,
#                                                     batch_first=True)
#         self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
#         # Output a single logit for real/fake classification
#         self.fc_out = nn.Linear(d_model, 1)
# 
#     def forward(self, src):
#         # src shape: (batch_size, sequence_length)
#         embedded = self.embedding(src) # (batch_size, sequence_length, d_model)
#         output = self.transformer_encoder(embedded) # (batch_size, sequence_length, d_model)
#         # Take the mean over the sequence length to get a single vector per sequence
#         pooled_output = output.mean(dim=1) # (batch_size, d_model)
#         logits = self.fc_out(pooled_output) # (batch_size, 1)
#         return logits
# 
# def weights_init(m):
#     """
#     Custom weight initialization for Generator and Discriminator.
#     Applies Xavier uniform to linear/embedding weights and zeros to biases.
#     """
#     classname = m.__class__.__name__
#     if classname.find('Linear') != -1 or classname.find('Embedding') != -1:
#         nn.init.xavier_uniform_(m.weight)
#         if hasattr(m, 'bias') and m.bias is not None:
#             nn.init.constant_(m.bias, 0)
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile preprocessing.py
# import torch
# import json
# import pathlib
# import pickle
# import numpy as np
# 
# def preprocess_and_cache_data(config):
#     """
#     Loads ARC tasks, converts grids to flattened sequences with special tokens,
#     pads them, and caches the processed data to disk.
#     """
#     processed_data_path = config['base_data_path'] / config['processed_data_file']
# 
#     if processed_data_path.exists():
#         print(f"Loading preprocessed data from {processed_data_path}")
#         with open(processed_data_path, 'rb') as f:
#             all_sequences, max_seq_len = pickle.load(f)
#         config['max_seq_len'] = max_seq_len # Update config with loaded max_seq_len
#         print(f"Loaded {len(all_sequences)} sequences. Max sequence length: {max_seq_len}")
#         return all_sequences
# 
#     print("Preprocessing data...")
#     task_files = list((config['base_data_path'] / config['input_directory']).glob('*.json'))
# 
#     all_sequences = []
#     max_seq_len = 0
# 
#     for task_file in task_files:
#         with open(task_file, 'r') as f:
#             task = json.load(f)
# 
#         for example in task['train']:
#             input_grid = np.array(example['input'], dtype=np.int32).flatten()
#             output_grid = np.array(example['output'], dtype=np.int32).flatten()
# 
#             # Sequence: [START_TOKEN, input_grid_tokens..., SEP_TOKEN, output_grid_tokens...]
#             sequence = [config['START_TOKEN']] + list(input_grid) + [config['SEP_TOKEN']] + list(output_grid)
#             all_sequences.append(torch.tensor(sequence, dtype=torch.long))
#             max_seq_len = max(max_seq_len, len(sequence))
# 
#         # Also process test examples to capture potential larger grids for sequence length
#         for example in task['test']:
#             input_grid = np.array(example['input'], dtype=np.int32).flatten()
#             # For test, we only know the input, the output is what we predict.
#             # But we still need to know potential max output size for padding.
#             # For training, we assume target output will be similar to train outputs.
#             # Let's just consider input_grid for max_seq_len calculation here for test part.
#             sequence_len_test_input = len(input_grid) + 2 # START_TOKEN, SEP_TOKEN
#             max_seq_len = max(max_seq_len, sequence_len_test_input + config['grid_size'] * config['grid_size']) # Assuming max possible output size
# 
#     # Pad all sequences to max_seq_len
#     padded_sequences = []
#     for seq in all_sequences:
#         padded_seq = F.pad(seq, (0, max_seq_len - len(seq)), value=config['PAD_TOKEN'])
#         padded_sequences.append(padded_seq)
# 
#     config['max_seq_len'] = max_seq_len # Update config with the determined max_seq_len
#     print(f"Preprocessing complete. Total sequences: {len(padded_sequences)}. Max sequence length: {max_seq_len}")
# 
#     print(f"Caching preprocessed data to {processed_data_path}")
#     with open(processed_data_path, 'wb') as f:
#         pickle.dump((padded_sequences, max_seq_len), f)
# 
#     return padded_sequences
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile gan_trainer.py
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from torch.utils.data import DataLoader
# from sklearn.model_selection import KFold
# import pathlib
# import json
# import matplotlib.pyplot as plt
# import numpy as np
# import random
# 
# from models import Generator, Discriminator, weights_init
# from dataset import ARCDataset
# from config import CONFIG # Import CONFIG directly for tokens/device
# 
# class GANTrainer:
#     """
#     Manages the GAN training process, including cross-validation,
#     model checkpointing, and visualization.
#     """
#     def __init__(self, config, all_sequences):
#         self.config = config
#         self.all_sequences = all_sequences
#         self.device = config['device']
#         self.output_dir = config['output_directory']
#         self.final_generator = None # To store the best generator after CV
# 
#         print(f"Using device: {self.device}")
# 
#     def save_checkpoint(self, generator, discriminator, optimizer_G, optimizer_D,
#                        scheduler_G, scheduler_D, epoch, fold):
#         """Saves the current state of models, optimizers, and schedulers."""
#         checkpoint_path = self.output_dir / f'gan_checkpoint_fold_{fold}_epoch_{epoch}.pth'
#         torch.save({
#             'epoch': epoch,
#             'generator_state_dict': generator.state_dict(),
#             'discriminator_state_dict': discriminator.state_dict(),
#             'optimizer_G_state_dict': optimizer_G.state_dict(),
#             'optimizer_D_state_dict': optimizer_D.state_dict(),
#             'scheduler_G_state_dict': scheduler_G.state_dict(),
#             'scheduler_D_state_dict': scheduler_D.state_dict(),
#         }, checkpoint_path)
#         print(f"Checkpoint saved for fold {fold}, epoch {epoch} to {checkpoint_path}")
# 
#     def load_checkpoint(self, generator, discriminator, optimizer_G, optimizer_D,
#                        scheduler_G, scheduler_D, fold):
#         """Loads the latest checkpoint for a given fold."""
#         checkpoints = sorted(self.output_dir.glob(f'gan_checkpoint_fold_{fold}_epoch_*.pth'), reverse=True)
#         if checkpoints:
#             latest_checkpoint = checkpoints[0]
#             print(f"Loading checkpoint from {latest_checkpoint}")
#             checkpoint = torch.load(latest_checkpoint, map_location=self.device)
#             generator.load_state_dict(checkpoint['generator_state_dict'])
#             discriminator.load_state_dict(checkpoint['discriminator_state_dict'])
#             optimizer_G.load_state_dict(checkpoint['optimizer_G_state_dict'])
#             optimizer_D.load_state_dict(checkpoint['optimizer_D_state_dict'])
#             scheduler_G.load_state_dict(checkpoint['scheduler_G_state_dict'])
#             scheduler_D.load_state_dict(checkpoint['scheduler_D_state_dict'])
#             print(f"Resuming training from epoch {checkpoint['epoch'] + 1}")
#             return checkpoint['epoch'] + 1
#         print(f"No checkpoint found for fold {fold}. Starting from epoch 1.")
#         return 1
# 
#     def train_one_fold(self, fold, train_loader):
#         """Trains the GAN for a single fold."""
#         generator = Generator(vocab_size=self.config['vocab_size'],
#                               d_model=self.config['d_model'],
#                               nhead=self.config['nhead'],
#                               num_layers=self.config['num_encoder_layers'],
#                               dim_feedforward=self.config['dim_feedforward'],
#                               dropout=self.config['dropout']).to(self.device)
#         discriminator = Discriminator(vocab_size=self.config['vocab_size'],
#                                    d_model=self.config['d_model'],
#                                    nhead=self.config['nhead'],
#                                    num_layers=self.config['num_encoder_layers'],
#                                    dim_feedforward=self.config['dim_feedforward'],
#                                    dropout=self.config['dropout']).to(self.device)
# 
#         generator.apply(weights_init)
#         discriminator.apply(weights_init)
# 
#         optimizer_G = optim.Adam(generator.parameters(), lr=self.config['gan_learning_rate'], weight_decay=self.config['gan_weight_decay'])
#         optimizer_D = optim.Adam(discriminator.parameters(), lr=self.config['gan_learning_rate'], weight_decay=self.config['gan_weight_decay'])
# 
#         scheduler_G = optim.lr_scheduler.StepLR(optimizer_G, step_size=self.config['gan_scheduler_step_size'], gamma=self.config['gan_scheduler_gamma'])
#         scheduler_D = optim.lr_scheduler.StepLR(optimizer_D, step_size=self.config['gan_scheduler_step_size'], gamma=self.config['gan_scheduler_gamma'])
# 
#         criterion = nn.BCEWithLogitsLoss()
#         cross_entropy_loss = nn.CrossEntropyLoss(ignore_index=self.config['PAD_TOKEN']) # For G's prediction objective
# 
#         start_epoch = self.load_checkpoint(generator, discriminator, optimizer_G, optimizer_D,
#                                           scheduler_G, scheduler_D, fold)
# 
#         fold_discriminator_losses = []
#         fold_generator_losses = []
# 
#         for epoch in range(start_epoch, self.config['gan_num_epochs'] + 1):
#             generator.train()
#             discriminator.train()
#             total_d_loss = 0
#             total_g_loss = 0
# 
#             for batch_idx, real_sequences in enumerate(train_loader):
#                 real_sequences = real_sequences.to(self.device)
#                 batch_size = real_sequences.size(0)
# 
#                 # --- Train Discriminator ---
#                 optimizer_D.zero_grad()
# 
#                 # 1. Train with real sequences
#                 real_labels = torch.ones(batch_size, 1, device=self.device)
#                 outputs_real = discriminator(real_sequences)
#                 d_loss_real = criterion(outputs_real, real_labels)
# 
#                 # 2. Train with fake sequences
#                 # Generate fake sequences from the generator
#                 # For training, the generator should predict next tokens based on previous ones,
#                 # but for simplicity in GAN, we can just generate a full sequence from a dummy input
#                 # or sample from the full distribution. A more robust way would be to
#                 # use teacher forcing for input, and generate output.
#                 # Here, we'll try to generate coherent sequences.
#                 # Provide a starting token and part of real_sequences as input to generator
# 
#                 # A common approach for sequence GANs (like SeqGAN) is to use policy gradient
#                 # to train the generator. Here, we're using a simpler approach where
#                 # G generates a full sequence and D judges it.
#                 # To make G generate "coherently", we can feed it START_TOKEN and input part.
# 
#                 # Simplified generation: just get output from generator on the real sequences
#                 # This makes generator try to "reconstruct" the input-output mapping
#                 # or produce plausible sequences from random noise.
#                 # Let's use real_sequences as source for Generator to learn to imitate the data distribution.
#                 # The generator isn't conditioned on random noise here, but on the sequence structure.
# 
#                 # Option 1: Generate from start token
#                 # This is more aligned with generating new data from scratch
#                 seed_input = torch.full((batch_size, self.config['max_seq_len']), self.config['PAD_TOKEN'], dtype=torch.long, device=self.device)
#                 seed_input[:, 0] = self.config['START_TOKEN'] # Start with START_TOKEN
# 
#                 # For simplicity, let generator produce a full sequence in one go (like a VAE decoder)
#                 # This is a bit of a simplification for typical sequence generation, but works for the adversarial objective.
#                 # A more complex G might generate tokens one by one or condition on more detailed input.
#                 with torch.no_grad(): # Discriminator trains on fixed fake samples
#                     fake_sequences_logits = generator(seed_input) # Generate logits
#                     fake_sequences = torch.argmax(fake_sequences_logits, dim=-1) # (batch_size, sequence_length)
# 
#                 # Clamp generated tokens to valid range for embedding layer safety
#                 fake_sequences = torch.clamp(fake_sequences, 0, self.config['vocab_size'] - 1)
# 
#                 fake_labels = torch.zeros(batch_size, 1, device=self.device)
#                 outputs_fake = discriminator(fake_sequences)
#                 d_loss_fake = criterion(outputs_fake, fake_labels)
# 
#                 d_loss = d_loss_real + d_loss_fake
#                 d_loss.backward()
#                 torch.nn.utils.clip_grad_norm_(discriminator.parameters(), self.config['gan_gradient_clip_val'])
#                 optimizer_D.step()
#                 total_d_loss += d_loss.item()
# 
#                 # --- Train Generator ---
#                 optimizer_G.zero_grad()
# 
#                 # Generator tries to fool the discriminator AND optionally reconstruct data
#                 # For GAN, we want G to produce samples D classifies as real.
#                 # The input to generator for this step can be the same seed_input as above
#                 generated_logits = generator(seed_input)
# 
#                 # Use CrossEntropyLoss to make the generator output distribution close to what would be real tokens
#                 # This provides a strong signal for the generator to learn plausible sequences
#                 # The target for this CE loss would be the real_sequences (teacher forcing)
#                 # However, for pure GAN, G just tries to fool D.
#                 # To make G generate realistic sequences, a combination of GAN loss and some form of reconstruction/MLE loss is often used.
# 
#                 # GAN loss for generator: make discriminator classify fake as real
#                 fake_sequences_for_g = torch.argmax(generated_logits, dim=-1)
#                 fake_sequences_for_g = torch.clamp(fake_sequences_for_g, 0, self.config['vocab_size'] - 1)
# 
#                 outputs_fake_for_g = discriminator(fake_sequences_for_g)
#                 g_loss_adv = criterion(outputs_fake_for_g, real_labels) # Generator wants D to output 1 (real)
# 
#                 # Optional: Add a reconstruction/MLE loss component to generator
#                 # This helps stabilize training and ensure G learns to produce *meaningful* sequences
#                 # target for reconstruction is `real_sequences`
#                 # We need to predict `real_sequences[:, 1:]` from `real_sequences[:, :-1]`
# 
#                 # For a Transformer encoder based generator which processes the full sequence at once:
#                 # the goal is that generated_logits[i, j, k] is high for the correct token k at position j.
#                 # This implies generating the *entire* sequence to match real_sequences.
# 
#                 # Reshape logits to (batch_size * sequence_length, vocab_size)
#                 # Reshape targets to (batch_size * sequence_length)
#                 g_loss_mle = cross_entropy_loss(generated_logits.view(-1, self.config['vocab_size']), real_sequences.view(-1))
# 
#                 # Combine losses (hyperparameter alpha could control balance)
#                 alpha = 0.5 # Weight for MLE loss
#                 g_loss = g_loss_adv + alpha * g_loss_mle
# 
#                 g_loss.backward()
#                 torch.nn.utils.clip_grad_norm_(generator.parameters(), self.config['gan_gradient_clip_val'])
#                 optimizer_G.step()
#                 total_g_loss += g_loss.item()
# 
#             avg_d_loss = total_d_loss / len(train_loader)
#             avg_g_loss = total_g_loss / len(train_loader)
#             fold_discriminator_losses.append(avg_d_loss)
#             fold_generator_losses.append(avg_g_loss)
# 
#             print(f"Fold {fold}, Epoch {epoch}/{self.config['gan_num_epochs']} | D Loss: {avg_d_loss:.4f} | G Loss: {avg_g_loss:.4f}")
# 
#             scheduler_G.step()
#             scheduler_D.step()
# 
#             if epoch % self.config['gan_checkpoint_interval'] == 0 or epoch == self.config['gan_num_epochs']:
#                 self.save_checkpoint(generator, discriminator, optimizer_G, optimizer_D,
#                                     scheduler_G, scheduler_D, epoch, fold)
# 
#         # Save the final generator for this fold
#         self.save_model(generator, f'generator_fold_{fold}.pth')
#         print(f"Finished training fold {fold}. Generator saved.")
#         return fold_discriminator_losses, fold_generator_losses, generator # Return the trained generator
# 
#     def run_cross_validation(self):
#         """Runs K-fold cross-validation for GAN training."""
#         kf = KFold(n_splits=self.config['gan_k_folds'], shuffle=True, random_state=42)
#         all_fold_discriminator_losses = []
#         all_fold_generator_losses = []
#         trained_generators = []
# 
#         for fold, (train_index, val_index) in enumerate(kf.split(self.all_sequences)):
#             print(f"\n--- Training Fold {fold + 1}/{self.config['gan_k_folds']} ---")
#             train_sequences = [self.all_sequences[i] for i in train_index]
#             # Validation set not directly used in GAN loss, but useful for monitoring or early stopping
#             # For simplicity, we just train on the full training split of the fold.
# 
#             train_dataset = ARCDataset(train_sequences)
#             train_loader = DataLoader(train_dataset, batch_size=self.config['gan_batch_size'], shuffle=True)
# 
#             fold_d_losses, fold_g_losses, generator_model = self.train_one_fold(fold + 1, train_loader)
#             all_fold_discriminator_losses.append(fold_d_losses)
#             all_fold_generator_losses.append(fold_g_losses)
#             trained_generators.append(generator_model)
# 
#         avg_disc_loss_cv = np.mean([losses[-1] for losses in all_fold_discriminator_losses]) # Avg last epoch loss
#         avg_gen_loss_cv = np.mean([losses[-1] for losses in all_fold_generator_losses]) # Avg last epoch loss
# 
#         print(f"\n--- Cross-Validation Results ---")
#         print(f"Average Discriminator Loss (last epoch): {avg_disc_loss_cv:.4f}")
#         print(f"Average Generator Loss (last epoch): {avg_gen_loss_cv:.4f}")
# 
#         self.save_results(all_fold_discriminator_losses, all_fold_generator_losses, avg_disc_loss_cv, avg_gen_loss_cv)
# 
#         # Select the generator from the last fold for subsequent RL training, or an ensemble.
#         # For simplicity, we'll use the last one.
#         self.final_generator = trained_generators[-1]
#         self.save_model(self.final_generator, 'final_gan_generator.pth')
#         print("Final GAN Generator (from last fold) saved.")
# 
#         return self.final_generator
# 
#     def save_model(self, model, file_name):
#         """Saves a model's state dictionary."""
#         torch.save(model.state_dict(), self.output_dir / file_name)
# 
#     def save_results(self, fold_discriminator_losses, fold_generator_losses, avg_disc_loss_cv, avg_gen_loss_cv):
#         """Saves cross-validation results to a JSON file."""
#         results = {
#             'fold_discriminator_losses': fold_discriminator_losses,
#             'fold_generator_losses': fold_generator_losses,
#             'avg_discriminator_loss_cv': avg_disc_loss_cv,
#             'avg_generator_loss_cv': avg_gen_loss_cv
#         }
#         with open(self.output_dir / 'cross_validation_results.json', 'w') as f:
#             json.dump(results, f, indent=4)
# 
#     def visualize_grid(self, grid_sequence, ax, title="Generated Grid"):
#         """Visualizes a flattened grid sequence as a 2D grid."""
#         # Find the SEP_TOKEN to isolate the output grid
#         sep_idx = (grid_sequence == self.config['SEP_TOKEN']).nonzero(as_tuple=True)[0]
#         if len(sep_idx) == 0:
#             output_start_idx = 0 # No SEP token, assume whole sequence is output (or error)
#             print(f"Warning: No SEP_TOKEN found in sequence for visualization '{title}'. Showing whole sequence.")
#             grid_flat = grid_sequence[1:] # Skip START_TOKEN if it exists
#         else:
#             output_start_idx = sep_idx[0].item() + 1
#             grid_flat = grid_sequence[output_start_idx:]
# 
#         # Remove padding
#         grid_flat = grid_flat[grid_flat != self.config['PAD_TOKEN']]
# 
#         # Try to infer grid dimensions, assuming square or common ARC dimensions
#         # This is a heuristic. Actual ARC tasks have variable sizes.
#         side_len = int(np.sqrt(len(grid_flat)))
#         if side_len * side_len == len(grid_flat) and side_len > 0:
#             grid = grid_flat.reshape(side_len, side_len)
#         elif len(grid_flat) > 0 and len(grid_flat) % self.config['grid_size'] == 0:
#             # Assume max_grid_size as one dimension if it fits
#             side_len_y = self.config['grid_size']
#             side_len_x = len(grid_flat) // self.config['grid_size']
#             grid = grid_flat.reshape(side_len_y, side_len_x)
#         else:
#             # Fallback to a single row if dimensions can't be easily inferred or too large
#             if len(grid_flat) == 0:
#                 grid = np.zeros((1, 1), dtype=np.int32) + self.config['PAD_TOKEN'] # Show an empty square
#             elif len(grid_flat) > 1000: # Arbitrary large number to avoid huge plots
#                 grid = grid_flat[:100].reshape(10, 10) # Show a small part
#             else:
#                 grid = grid_flat.reshape(1, -1) # Single row
#             print(f"Warning: Could not infer 2D shape for grid in '{title}'. Displaying as 1D or partial. Length: {len(grid_flat)}")
# 
# 
#         # Convert to numpy and plot
#         grid_np = grid.cpu().numpy()
#         ax.imshow(grid_np, cmap='viridis', vmin=0, vmax=9) # ARC colors 0-9
#         ax.set_title(title)
#         ax.set_xticks([])
#         ax.set_yticks([])
# 
#     def generate_and_visualize_samples(self, num_samples=5):
#         """Generates sample sequences from the final generator and visualizes them."""
#         if self.final_generator is None:
#             print("No final generator available. Run cross_validation first.")
#             return
# 
#         self.final_generator.eval()
#         print(f"\n--- Generating and visualizing {num_samples} samples ---")
# 
#         fig, axes = plt.subplots(1, num_samples, figsize=(num_samples * 4, 4))
#         if num_samples == 1: # Handle case of single subplot
#             axes = [axes]
# 
#         with torch.no_grad():
#             for i in range(num_samples):
#                 # Create a dummy input sequence for generation
#                 # Start with START_TOKEN, rest padded
#                 seed_input = torch.full((1, self.config['max_seq_len']), self.config['PAD_TOKEN'], dtype=torch.long, device=self.device)
#                 seed_input[0, 0] = self.config['START_TOKEN']
# 
#                 generated_logits = self.final_generator(seed_input)
#                 generated_sequence = torch.argmax(generated_logits, dim=-1).squeeze(0) # (max_seq_len,)
# 
#                 self.visualize_grid(generated_sequence, axes[i], title=f'Sample {i+1}')
# 
#         plt.tight_layout()
#         plt.savefig(self.output_dir / 'gan_generated_samples.png')
#         plt.show()
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rl_agent.py
# import torch
# import torch.nn as nn
# import torch.optim as optim
# import random
# import pathlib
# 
# from models import Generator # Policy network is a Generator
# from config import CONFIG # Import CONFIG directly for tokens/device
# 
# class RLAgent(nn.Module):
#     """
#     Reinforcement Learning Agent using the Generator as its policy network.
#     It learns to select actions (sequences of tokens) based on rewards from the environment.
#     """
#     def __init__(self, generator: Generator, config):
#         super(RLAgent, self).__init__()
#         self.generator = generator # The policy network
#         self.config = config
#         self.device = config['device']
#         self.optimizer = optim.Adam(self.generator.parameters(), lr=config['rl_learning_rate'])
#         self.epsilon = config['epsilon_start'] # For epsilon-greedy exploration
#         self.epsilon_min = config['epsilon_min']
#         self.epsilon_decay = config['epsilon_decay']
# 
#         # Store log probabilities for policy gradient calculation
#         self.log_probs = []
#         self.rewards = []
# 
#     def forward(self, state):
#         """
#         Predicts logits for the entire sequence given an initial state.
#         This is essentially the Generator's forward pass.
#         State typically contains [START_TOKEN, input_grid, SEP_TOKEN, PADs...]
#         """
#         return self.generator(state)
# 
#     def select_action(self, state):
#         """
#         Selects an action (a sequence of tokens) using epsilon-greedy strategy.
#         An action is the complete generated sequence.
#         """
#         state = state.to(self.device)
# 
#         if random.random() < self.epsilon:
#             # Explore: generate a random sequence (within vocab and max_seq_len)
#             action_sequence = torch.randint(0, self.config['vocab_size'],
#                                            (1, self.config['max_seq_len']),
#                                            dtype=torch.long, device=self.device)
#             # Ensure START_TOKEN and SEP_TOKEN structure (optional but helps)
#             action_sequence[0, 0] = self.config['START_TOKEN']
#             if self.config['max_seq_len'] > 1:
#                 # Find where input part ends based on actual input grid length
#                 # This assumes 'state' contains actual input data up to SEP_TOKEN.
#                 # The 'state' typically comes from ARCEnvironment.reset()
#                 sep_idx = (state[0] == self.config['SEP_TOKEN']).nonzero(as_tuple=True)[0]
#                 if len(sep_idx) > 0:
#                     sep_idx = sep_idx[0].item()
#                     action_sequence[0, sep_idx] = self.config['SEP_TOKEN'] # Ensure SEP_TOKEN is there
#                     # Pad before SEP_TOKEN if random put tokens there
#                     action_sequence[0, 1:sep_idx] = state[0, 1:sep_idx] # Keep input part from state
# 
#             # For random generation, we don't store log_probs for policy gradient
#             self.log_probs.append(None) # Placeholder
# 
#         else:
#             # Exploit: use the generator to predict
#             self.generator.eval() # Set generator to evaluation mode
#             with torch.no_grad(): # Don't compute gradients for action selection
#                 logits = self.generator(state) # (1, max_seq_len, vocab_size)
# 
#             # Sample from the categorical distribution for each token
#             probs = F.softmax(logits, dim=-1) # (1, max_seq_len, vocab_size)
# 
#             # For REINFORCE, we need to sample actions and record their log probabilities.
#             # This is a bit tricky for a Transformer that outputs all tokens at once.
#             # We'll sample each token independently for simplicity,
#             # but a true sequential generation would sample one by one.
# 
#             # Sampling from Categorical distribution
#             dist = torch.distributions.Categorical(probs)
#             action_sequence = dist.sample() # (1, max_seq_len)
# 
#             # Calculate log probabilities for the selected actions
#             log_prob = dist.log_prob(action_sequence) # (1, max_seq_len)
#             self.log_probs.append(log_prob)
# 
#         self.generator.train() # Set generator back to training mode
#         return action_sequence # (1, max_seq_len)
# 
#     def update_policy(self, states, actions, rewards):
#         """
#         Updates the generator's policy using the REINFORCE algorithm.
#         States, actions, and rewards are batches collected over an episode.
#         """
#         self.optimizer.zero_grad()
# 
#         # Policy gradient loss for REINFORCE: sum(log_prob * reward)
#         # In this setup, we have one state -> one action (sequence) -> one reward.
#         # We accumulate log_probs for a sequence, and apply the single reward for that sequence.
# 
#         # Filter out None log_probs from exploration steps
#         valid_log_probs = [lp for lp in self.log_probs if lp is not None]
# 
#         if not valid_log_probs:
#             # All actions were random exploration, no policy to update.
#             print("No valid log probabilities to update policy.")
#             self.log_probs = []
#             self.rewards = []
#             return 0.0
# 
#         policy_loss = 0
# 
#         # Assuming rewards is a list of scalars, and log_probs is a list of (1, max_seq_len) tensors
#         # Each element in valid_log_probs corresponds to one full generated sequence (action) and one reward.
# 
#         # We need to compute log_probs again based on the agent's current policy
#         # because the policy might have changed due to previous updates.
#         # This is typically done if rewards are batched.
#         # For single-step episodes like ARC tasks, we can just use the stored log_probs
#         # multiplied by the single reward received for that action.
#         # G_t = sum(gamma^k * r_t+k) -- but for single step, G_t is just r_t
# 
#         for lp_seq, r in zip(valid_log_probs, rewards):
#             # Sum log_probs for the entire sequence and multiply by the episode's total reward
#             # The REINFORCE objective maximizes expected total reward.
#             # -log(pi(a|s)) * G_t, where G_t is the return.
#             # If r is already the return (total reward for that action sequence), then:
#             policy_loss += (-lp_seq.sum() * r) # Negative sign for gradient ascent (maximizing reward)
# 
#         # Average over the collected samples
#         policy_loss /= len(valid_log_probs)
# 
#         policy_loss.backward()
#         torch.nn.utils.clip_grad_norm_(self.generator.parameters(), self.config['gan_gradient_clip_val']) # Re-use GAN clip val
#         self.optimizer.step()
# 
#         self.log_probs = [] # Clear for next episode
#         self.rewards = [] # Clear for next episode
# 
#         return policy_loss.item()
# 
#     def decay_epsilon(self):
#         """Decays the exploration rate epsilon."""
#         self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
# 
# 
# # --- Helper functions for RL checkpointing ---
# 
# def save_rl_model(model, file_name, config):
#     """Saves the final RL Generator model."""
#     rl_output_dir = pathlib.Path(config['rl_output_directory'])
#     rl_output_dir.mkdir(parents=True, exist_ok=True)
#     torch.save(model.state_dict(), rl_output_dir / file_name)
#     print(f"RL Generator saved to {rl_output_dir / file_name}")
# 
# def save_rl_checkpoint(agent: RLAgent, episode, config):
#     """Saves an RL agent's checkpoint."""
#     rl_output_dir = pathlib.Path(config['rl_output_directory'])
#     checkpoint_path = rl_output_dir / f'rl_checkpoint_episode_{episode}.pth'
#     torch.save({
#         'episode': episode,
#         'generator_state_dict': agent.generator.state_dict(),
#         'optimizer_state_dict': agent.optimizer.state_dict(),
#         'epsilon': agent.epsilon,
#     }, checkpoint_path)
#     print(f"RL checkpoint saved for episode {episode} to {checkpoint_path}")
# 
# def load_rl_checkpoint(agent: RLAgent, config):
#     """Loads the latest RL agent checkpoint."""
#     rl_output_dir = pathlib.Path(config['rl_output_directory'])
#     checkpoints = sorted(rl_output_dir.glob('rl_checkpoint_episode_*.pth'), reverse=True)
#     if checkpoints:
#         latest_checkpoint = checkpoints[0]
#         print(f"Loading RL checkpoint from {latest_checkpoint}")
#         checkpoint = torch.load(latest_checkpoint, map_location=agent.device)
#         agent.generator.load_state_dict(checkpoint['generator_state_dict'])
#         agent.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
#         agent.epsilon = checkpoint['epsilon']
#         print(f"Resuming RL training from episode {checkpoint['episode'] + 1}")
#         return checkpoint['episode'] + 1
#     print("No RL checkpoint found. Starting RL training from episode 1.")
#     return 1
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile arc_environment.py
# import torch
# import numpy as np
# import json
# import random
# from config import CONFIG # Import CONFIG directly for tokens/device
# 
# class ARCEnvironment:
#     """
#     Simulates the ARC environment for an RL agent.
#     Provides states (input grids) and calculates rewards based on generated output.
#     """
#     def __init__(self, config, arc_tasks):
#         self.config = config
#         self.arc_tasks = arc_tasks
#         self.current_task_idx = -1
#         self.current_task = None
#         self.target_output_grid = None
#         self.device = config['device']
#         self.max_seq_len = config['max_seq_len'] # Ensure this is set by preprocessing
# 
#         # Token constants
#         self.START_TOKEN = config['START_TOKEN']
#         self.SEP_TOKEN = config['SEP_TOKEN']
#         self.PAD_TOKEN = config['PAD_TOKEN']
#         self.REWARD_CORRECT_PIXEL = config['reward_correct_pixel']
#         self.REWARD_WRONG_PIXEL = config['reward_wrong_pixel']
#         self.REWARD_SHAPE_MISMATCH = config['reward_shape_mismatch']
# 
#     def reset(self):
#         """
#         Resets the environment for a new episode (new ARC task).
#         Selects a new task and returns its input grid as the initial state.
#         """
#         if not self.arc_tasks:
#             print("No ARC tasks available to reset.")
#             return None, None # Indicate no more tasks
# 
#         self.current_task_idx = (self.current_task_idx + 1) % len(self.arc_tasks)
#         self.current_task = self.arc_tasks[self.current_task_idx]
# 
#         # For RL, we use the training examples from ARC tasks
#         # Each training example within a task is a separate "episode" for the RL agent
#         # We need to choose one specific example to train on per episode
#         example_idx = random.randrange(len(self.current_task['train']))
#         train_example = self.current_task['train'][example_idx]
# 
#         input_grid = np.array(train_example['input'], dtype=np.int32)
#         self.target_output_grid = np.array(train_example['output'], dtype=np.int32)
# 
#         # Flatten input grid and prepare state sequence
#         input_flat = input_grid.flatten()
#         state_sequence = [self.START_TOKEN] + list(input_flat) + [self.SEP_TOKEN]
# 
#         # Pad the state sequence to max_seq_len
#         state_tensor = torch.full((1, self.max_seq_len), self.PAD_TOKEN, dtype=torch.long, device=self.device)
#         state_tensor[0, :len(state_sequence)] = torch.tensor(state_sequence, dtype=torch.long, device=self.device)
# 
#         return state_tensor
# 
#     def _extract_output_grid(self, action_sequence):
#         """
#         Extracts the predicted output grid from the agent's full generated sequence.
#         Assumes sequence format: [START_TOKEN, input_grid_tokens..., SEP_TOKEN, output_grid_tokens...]
#         """
#         action_sequence_cpu = action_sequence.cpu().numpy().flatten()
# 
#         # Find the SEP_TOKEN to delineate input and output parts
#         sep_indices = np.where(action_sequence_cpu == self.SEP_TOKEN)[0]
# 
#         if len(sep_indices) == 0:
#             # If SEP_TOKEN is missing, assume the entire sequence after START_TOKEN is output (or handle as error)
#             # For robust training, ensure agent learns to place SEP_TOKEN
#             # This can result in a harsh penalty.
#             return None # Indicate extraction failure
# 
#         sep_idx = sep_indices[0]
# 
#         # The output part starts after the SEP_TOKEN
#         output_flat_sequence = action_sequence_cpu[sep_idx + 1:]
# 
#         # Remove padding tokens from the end
#         output_flat_sequence = output_flat_sequence[output_flat_sequence != self.PAD_TOKEN]
# 
#         return output_flat_sequence
# 
#     def step(self, action_sequence):
#         """
#         Takes an action (generated sequence) from the agent and calculates the reward.
#         """
#         predicted_output_flat = self._extract_output_grid(action_sequence)
# 
#         reward = 0.0
#         done = True # Each ARC task example is a single-step episode
# 
#         if predicted_output_flat is None:
#             # Major structural error, e.g., missing SEP_TOKEN
#             reward = self.REWARD_SHAPE_MISMATCH * 2 # Heavier penalty
#             return reward, done
# 
#         # Try to reshape the predicted output flat array to match the target's shape
#         target_shape = self.target_output_grid.shape
#         target_flat_len = self.target_output_grid.size
# 
#         if predicted_output_flat.size != target_flat_len:
#             # Shape mismatch penalty
#             reward += self.REWARD_SHAPE_MISMATCH
#             # Pad or truncate predicted_output_flat to target_flat_len for pixel-wise comparison
#             # This allows some pixel-wise reward even with shape mismatch
#             if predicted_output_flat.size > target_flat_len:
#                 predicted_output_flat = predicted_output_flat[:target_flat_len]
#             else:
#                 predicted_output_flat = np.pad(predicted_output_flat, (0, target_flat_len - predicted_output_flat.size),
#                                                mode='constant', constant_values=self.PAD_TOKEN)
# 
# 
#         # Compare pixel by pixel
#         correct_pixels = np.sum(predicted_output_flat == self.target_output_grid.flatten())
#         wrong_pixels = target_flat_len - correct_pixels
# 
#         reward += correct_pixels * self.REWARD_CORRECT_PIXEL
#         reward += wrong_pixels * self.REWARD_WRONG_PIXEL
# 
#         return reward, done
# 
#     def get_all_tasks(self, task_dir_name):
#         """Loads all ARC tasks from a specified directory (e.g., 'training' or 'evaluation')."""
#         task_files = list((self.config['base_data_path'] / task_dir_name).glob('*.json'))
#         all_tasks = []
#         for task_file in task_files:
#             with open(task_file, 'r') as f:
#                 all_tasks.append(json.load(f))
#         return all_tasks
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile rl_trainer.py
# import torch
# import json
# import pathlib
# import matplotlib.pyplot as plt
# import numpy as np
# 
# from rl_agent import RLAgent, save_rl_model, save_rl_checkpoint, load_rl_checkpoint
# from arc_environment import ARCEnvironment
# from config import CONFIG # Import CONFIG directly for device
# 
# def train_rl_agent(agent: RLAgent, env: ARCEnvironment, config):
#     """
#     Main training loop for the Reinforcement Learning agent.
#     Interacts with the environment, collects rewards, and updates the policy.
#     """
#     print(f"\n--- Starting RL Training ---")
#     start_episode = load_rl_checkpoint(agent, config)
# 
#     episode_rewards = []
#     policy_losses = []
# 
#     # Store history for plotting
#     history_rewards = []
#     history_avg_rewards = []
#     history_losses = []
# 
#     for episode in range(start_episode, config['rl_num_episodes'] + 1):
#         state = env.reset() # Get initial state (input grid) for a new task example
#         if state is None: # No more tasks in env, or error
#             print("No more tasks available in environment. Stopping RL training.")
#             break
# 
#         # Agent selects an action (full output sequence)
#         action_sequence = agent.select_action(state)
# 
#         # Environment returns reward for the generated sequence
#         reward, done = env.step(action_sequence)
# 
#         # Store reward for policy update
#         agent.rewards.append(reward)
# 
#         # Update policy
#         policy_loss = agent.update_policy(state, action_sequence, agent.rewards)
# 
#         episode_rewards.append(reward)
#         policy_losses.append(policy_loss)
# 
#         # Decay epsilon for exploration
#         agent.decay_epsilon()
# 
#         if episode % 100 == 0:
#             avg_reward = np.mean(episode_rewards[-100:])
#             print(f"Episode {episode}/{config['rl_num_episodes']} | Avg Reward (last 100): {avg_reward:.2f} | Policy Loss: {policy_loss:.4f} | Epsilon: {agent.epsilon:.2f}")
# 
#             history_rewards.append(reward)
#             history_avg_rewards.append(avg_reward)
#             history_losses.append(policy_loss)
# 
#         if episode % config['rl_checkpoint_interval'] == 0 or episode == config['rl_num_episodes']:
#             save_rl_checkpoint(agent, episode, config)
# 
#     # Save final model
#     save_rl_model(agent.generator, 'final_rl_generator.pth', config)
# 
#     # Save training results
#     results = {
#         'episode_rewards': episode_rewards,
#         'policy_losses': policy_losses,
#         'final_epsilon': agent.epsilon,
#         'history_rewards': history_rewards,
#         'history_avg_rewards': history_avg_rewards,
#         'history_losses': history_losses
#     }
#     with open(config['rl_output_directory'] / 'rl_training_results.json', 'w') as f:
#         json.dump(results, f, indent=4)
# 
#     # Plotting results
#     plt.figure(figsize=(15, 5))
# 
#     plt.subplot(1, 3, 1)
#     plt.plot(episode_rewards)
#     plt.title('Episode Rewards')
#     plt.xlabel('Episode')
#     plt.ylabel('Reward')
#     plt.savefig(config['rl_output_directory'] / 'rl_episode_rewards.png')
# 
#     plt.subplot(1, 3, 2)
#     # Calculate rolling average for display
#     rolling_avg_rewards = np.convolve(episode_rewards, np.ones(100)/100, mode='valid')
#     plt.plot(rolling_avg_rewards)
#     plt.title('Rolling Average Rewards (100 episodes)')
#     plt.xlabel('Episode')
#     plt.ylabel('Average Reward')
#     plt.savefig(config['rl_output_directory'] / 'rl_avg_rewards.png')
# 
#     plt.subplot(1, 3, 3)
#     plt.plot(policy_losses)
#     plt.title('Policy Loss')
#     plt.xlabel('Episode')
#     plt.ylabel('Loss')
#     plt.savefig(config['rl_output_directory'] / 'rl_policy_loss.png')
# 
#     plt.tight_layout()
#     plt.show()
# 
#     print(f"RL training complete. Final model saved to {config['rl_output_directory'] / 'final_rl_generator.pth'}")
#     return agent.generator
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile submission.py
# import torch
# import json
# import pathlib
# import numpy as np
# 
# from models import Generator
# from config import CONFIG # Import CONFIG directly for tokens/device
# 
# def generate_submission_file(generator: Generator, config):
#     """
#     Generates predictions for ARC test tasks and formats them into a submission.json file.
#     """
#     print(f"\n--- Generating submission file ---")
#     generator.eval() # Set generator to evaluation mode
# 
#     test_tasks_dir = config['base_data_path'] / config['test_directory']
#     test_task_files = sorted(list(test_tasks_dir.glob('*.json')))
# 
#     predictions = []
# 
#     # Token constants
#     START_TOKEN = config['START_TOKEN']
#     SEP_TOKEN = config['SEP_TOKEN']
#     PAD_TOKEN = config['PAD_TOKEN']
#     MAX_SEQ_LEN = config['max_seq_len']
#     DEVICE = config['device']
# 
#     with torch.no_grad():
#         for task_file in test_task_files:
#             with open(task_file, 'r') as f:
#                 task = json.load(f)
# 
#             task_id = task_file.stem
#             current_task_predictions = []
# 
#             for example in task['test']:
#                 input_grid = np.array(example['input'], dtype=np.int32).flatten()
# 
#                 # Construct the input sequence for the generator
#                 # [START_TOKEN, input_grid_tokens..., SEP_TOKEN, PADs...]
#                 input_sequence_list = [START_TOKEN] + list(input_grid) + [SEP_TOKEN]
# 
#                 # Pad to MAX_SEQ_LEN
#                 input_tensor = torch.full((1, MAX_SEQ_LEN), PAD_TOKEN, dtype=torch.long, device=DEVICE)
#                 input_tensor[0, :len(input_sequence_list)] = torch.tensor(input_sequence_list, dtype=torch.long, device=DEVICE)
# 
#                 # Generate the full sequence
#                 generated_logits = generator(input_tensor)
#                 generated_sequence = torch.argmax(generated_logits, dim=-1).squeeze(0) # (MAX_SEQ_LEN,)
#                 generated_sequence_np = generated_sequence.cpu().numpy()
# 
#                 # Extract the output grid part
#                 sep_indices = np.where(generated_sequence_np == SEP_TOKEN)[0]
#                 if len(sep_indices) == 0:
#                     # If no SEP_TOKEN, prediction is ill-formed. Return empty or default.
#                     predicted_output_flat = []
#                     print(f"Warning: No SEP_TOKEN found in generated sequence for task {task_id}. Example input shape: {np.array(example['input']).shape}. Returning empty grid.")
#                 else:
#                     output_start_idx = sep_indices[0] + 1
#                     predicted_output_flat = generated_sequence_np[output_start_idx:]
#                     predicted_output_flat = predicted_output_flat[predicted_output_flat != PAD_TOKEN] # Remove padding
# 
#                 # Attempt to reshape the output grid
#                 # This is a heuristic. In ARC, output shape can be different from input and not necessarily square.
#                 # A more sophisticated approach would involve predicting output dimensions,
#                 # or trying common aspect ratios/sizes from training data.
# 
#                 # For this submission, let's try to infer a square shape first.
#                 # If not square, try to infer based on input grid dimensions.
# 
#                 # A common heuristic is that output is often the same shape as input.
#                 input_h, input_w = np.array(example['input']).shape
# 
#                 predicted_grid = []
#                 if len(predicted_output_flat) > 0:
#                     output_h = input_h # Default to input height
#                     output_w = input_w # Default to input width
# 
#                     # Try to infer if it's a perfect square
#                     side_len = int(np.sqrt(len(predicted_output_flat)))
#                     if side_len * side_len == len(predicted_output_flat):
#                         output_h = output_w = side_len
#                     elif len(predicted_output_flat) % input_w == 0: # Check if it's a rectangle with input_w
#                         output_h = len(predicted_output_flat) // input_w
#                         output_w = input_w
#                     elif len(predicted_output_flat) % input_h == 0: # Check if it's a rectangle with input_h
#                         output_w = len(predicted_output_flat) // input_h
#                         output_h = input_h
#                     else: # Fallback: assume input_h x input_w or just a single row
#                         output_h = input_h
#                         output_w = input_w
#                         if len(predicted_output_flat) != output_h * output_w:
#                             # Truncate or pad to fit assumed dimensions
#                             if len(predicted_output_flat) > output_h * output_w:
#                                 predicted_output_flat = predicted_output_flat[:output_h * output_w]
#                             else:
#                                 predicted_output_flat = np.pad(predicted_output_flat, (0, output_h * output_w - len(predicted_output_flat)),
#                                                                mode='constant', constant_values=0) # Pad with 0s
# 
#                     try:
#                         predicted_grid = predicted_output_flat.reshape(output_h, output_w).tolist()
#                     except ValueError:
#                         print(f"Warning: Could not reshape output for task {task_id}, example {example['input']}. Flat len: {len(predicted_output_flat)}, target shape: ({output_h}, {output_w}). Returning empty grid.")
#                         predicted_grid = []
# 
#                 current_task_predictions.append({
#                     "output": predicted_grid
#                 })
# 
#             predictions.append({
#                 "task_id": task_id,
#                 "output": current_task_predictions
#             })
# 
#     submission_path = config['base_data_path'] / config['submission_file']
#     with open(submission_path, 'w') as f:
#         json.dump(predictions, f, indent=4)
# 
#     print(f"Submission file generated: {submission_path}")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# import os
# import pathlib
# import torch
# import json
# import numpy as np
# 
# # Import all modules
# from config import CONFIG
# from preprocessing import preprocess_and_cache_data
# from gan_trainer import GANTrainer
# from rl_agent import RLAgent
# from arc_environment import ARCEnvironment
# from rl_trainer import train_rl_agent
# from submission import generate_submission_file
# from models import Generator # To load trained model state_dict
# 
# if __name__ == '__main__':
#     print("--- Starting ARC Solver ---")
#     print(f"Running on device: {CONFIG['device']}")
# 
#     # 1. Preprocess and Cache Data
#     print("\nStep 1: Preprocessing data...")
#     all_sequences = preprocess_and_cache_data(CONFIG)
#     print(f"Max sequence length determined: {CONFIG['max_seq_len']}")
# 
#     # 2. Train GAN
#     print("\nStep 2: Initializing GAN Trainer...")
#     gan_trainer = GANTrainer(CONFIG, all_sequences)
# 
#     print("\nStep 2a: Running GAN Cross-Validation...")
#     final_gan_generator = gan_trainer.run_cross_validation()
# 
#     print("\nStep 2b: Visualizing GAN Generated Samples...")
#     gan_trainer.generate_and_visualize_samples(num_samples=5)
# 
#     # 3. Prepare for Reinforcement Learning
#     print("\nStep 3: Preparing for Reinforcement Learning...")
#     # Load the training tasks for the RL environment
#     temp_env = ARCEnvironment(CONFIG, []) # Create a temp env to load tasks
#     rl_training_tasks = temp_env.get_all_tasks(CONFIG['input_directory'])
# 
#     rl_env = ARCEnvironment(CONFIG, rl_training_tasks)
#     rl_agent = RLAgent(final_gan_generator, CONFIG) # Initialize RL agent with the GAN-trained generator
# 
#     # 4. Train RL Agent
#     print("\nStep 4: Training RL Agent...")
#     final_rl_generator = train_rl_agent(rl_agent, rl_env, CONFIG)
# 
#     # 5. Generate Submission File
#     print("\nStep 5: Generating Submission File...")
# 
#     # Reload the final RL generator to ensure clean state
#     # This also handles cases where RL training might have been skipped/restarted
#     submission_generator = Generator(vocab_size=CONFIG['vocab_size'],
#                                    d_model=CONFIG['d_model'],
#                                    nhead=CONFIG['nhead'],
#                                    num_layers=CONFIG['num_encoder_layers'],
#                                    dim_feedforward=CONFIG['dim_feedforward'],
#                                    dropout=CONFIG['dropout']).to(CONFIG['device'])
# 
#     rl_model_path = CONFIG['rl_output_directory'] / 'final_rl_generator.pth'
#     if rl_model_path.exists():
#         submission_generator.load_state_dict(torch.load(rl_model_path, map_location=CONFIG['device']))
#         print(f"Loaded final RL generator from {rl_model_path}")
#     else:
#         print(f"Warning: Final RL generator not found at {rl_model_path}. Using final GAN generator for submission.")
#         # Fallback to GAN generator if RL model not found
#         gan_model_path = CONFIG['output_directory'] / 'final_gan_generator.pth'
#         if gan_model_path.exists():
#             submission_generator.load_state_dict(torch.load(gan_model_path, map_location=CONFIG['device']))
#         else:
#             raise FileNotFoundError("Neither final RL nor GAN generator found. Cannot create submission.")
# 
#     generate_submission_file(submission_generator, CONFIG)
# 
#     print("\n--- ARC Solver Finished ---")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile run.py
# import sys
# import os
# 
# # Add the current directory to the Python path to allow importing local modules
# sys.path.append(os.path.dirname(__file__))
# 
# # Import the main execution function
# from main import run_arc_solver
# 
# if __name__ == '__main__':
#     print("Executing the ARC Solver pipeline via run.py...")
#     run_arc_solver()
#     print("run.py finished.")

!python main.py
!python run.py

