# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hps7VBdUpnpiQYfvWEW1QkQ2vfPMaF1b
"""

import os
import json
import numpy as np
import logging
import sys

import tensorflow as tf

from tensorflow.keras import layers, Model
from tensorflow.keras.initializers import GlorotNormal
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard
from tensorflow.keras.losses import SparseCategoricalCrossentropy

from google.colab import drive
drive.mount('/content/drive')

logging.basicConfig(level=logging.INFO, stream=sys.stdout, format='%(asctime)s - %(levelname)s - %(message)s')

class ARCConfig:
    """Centralized configuration for the ARC project, enhanced for a Multi-Tensor Compressor."""
    def __init__(self):
        self.project_root = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025'
        self.datasets_dir = os.path.join(self.project_root, 'datasets')
        self.training_challenges_path = os.path.join(self.datasets_dir, 'arc-agi_training_challenges.json')
        self.vae_checkpoints_dir = os.path.join(self.project_root, 'vae_checkpoints')
        self.grid_size = 30
        self.latent_dim = 128
        self.num_colors = 10
        self.epochs = 5
        self.batch_size = 32
        self.run_eagerly = False
        self.debug_mode = False
        self.verbose_logging = True
        self.use_one_hot_input = False
        self.output_discretization_method = "argmax"
        self.use_vector_quantization = False
        self.vq_num_embeddings = 512
        self.vq_embedding_dim = 64
        self.compressor_transformer_heads = 4
        self.compressor_transformer_layers = 2
        self.compressor_max_sequence_length = self.grid_size * self.grid_size
        self.compressor_artifacts_dir = os.path.join(self.project_root, 'compressor_artifacts')
        self.synthetic_data_paths = [
            os.path.join(self.datasets_dir, f'generated_dcgan_dataset_{size}x{size}.json')
            for size in [3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 16, 19, 20, 30]
        ]

class BaseDataLoader:
    """Base class for creating a tf.data.Dataset pipeline.
    Handles common pre-processing steps like padding, one-hot encoding, and batching.
    """
    def __init__(self, config):
        self.config = config

    def _pad_grid_tf(self, grid_tensor):
        """Pads or crops a grid tensor to a fixed square size (config.grid_size)."""
        height, width = tf.shape(grid_tensor)[0], tf.shape(grid_tensor)[1]

        # Calculate padding amounts
        # pad_height and pad_width are the amounts needed to reach config.grid_size
        pad_height = tf.maximum(0, self.config.grid_size - height)
        pad_width = tf.maximum(0, self.config.grid_size - width)

        # Pad only if needed (e.g., if current dim < target dim)
        padded_grid = tf.pad(
            grid_tensor,
            [[0, pad_height], [0, pad_width]],
            constant_values=0 # Use 0 for padding as it's a valid color and common background
        )

        # Crop if the original grid (or padded grid) is larger than the target size
        cropped_grid = padded_grid[:self.config.grid_size, :self.config.grid_size]

        return tf.cast(cropped_grid, dtype=tf.int32)

    def _get_data_generator(self):
        """Placeholder for a generator function, implemented by subclasses."""
        raise NotImplementedError("Subclasses must implement _get_data_generator.")

    def load_dataset(self):
        """Returns a batched, pre-processed tf.data.Dataset from the generator."""
        # Pass the method reference, not the result of calling the method
        ds = tf.data.Dataset.from_generator(
            self._get_data_generator,
            output_signature=tf.TensorSpec(shape=(None, None), dtype=tf.int32) # Grids of varying (H,W)
        )

        # Filter out empty or invalid grids early
        ds = ds.filter(lambda x: tf.rank(x) == 2 and tf.shape(x)[0] > 0 and tf.shape(x)[1] > 0)

        # Apply padding/cropping to a uniform size (e.g., 30x30)
        ds = ds.map(self._pad_grid_tf, num_parallel_calls=tf.data.AUTOTUNE)

        # --- Handle input representation (one-hot or single channel) ---
        if self.config.use_one_hot_input:
            # Cast to int64 for one_hot, then to float32 for model input
            ds = ds.map(lambda x: tf.one_hot(tf.cast(x, tf.int64), depth=self.config.num_colors, dtype=tf.float32),
                        num_parallel_calls=tf.data.AUTOTUNE)
            # Target shape for one-hot encoded input
            target_shape = tf.constant([self.config.grid_size, self.config.grid_size, self.config.num_colors], dtype=tf.int32)
        else:
            # Add a channel dimension (e.g., (H, W) -> (H, W, 1))
            ds = ds.map(lambda x: tf.expand_dims(x, axis=-1), num_parallel_calls=tf.data.AUTOTUNE)
            # Target shape for integer input
            target_shape = tf.constant([self.config.grid_size, self.config.grid_size, 1], dtype=tf.int32)
        # --- END Input Representation ---

        # Ensure and filter by target shape for robustness
        # Removed the problematic tf.ensure_shape call within map
        ds = ds.filter(lambda x: tf.reduce_all(tf.equal(tf.shape(x), target_shape)))

        ds = ds.shuffle(buffer_size=5000)
        ds = ds.batch(self.config.batch_size)
        ds = ds.prefetch(tf.data.AUTOTUNE)
        return ds

class ARCDataLoader(BaseDataLoader):
    """Data loader for the official ARC training challenges."""
    def _get_data_generator(self):
        """Loads grids from the official ARC training challenges JSON file."""
        try:
            with open(self.config.training_challenges_path, 'r') as f:
                full_data = json.load(f)
        except FileNotFoundError:
            logging.error(f"ARC training challenges file not found at: {self.config.training_challenges_path}")
            sys.exit(1) # Exit if essential file is missing
        except json.JSONDecodeError as e:
            logging.error(f"Error decoding JSON from {self.config.training_challenges_path}: {e}")
            sys.exit(1)

        logging.info(f"Loading ARC training challenges from {self.config.training_challenges_path}")
        for task_id, task_data in full_data.items():
            for example in task_data.get('train', []):
                if 'output' in example and example['output'] is not None:
                    # Convert list of lists to NumPy array
                    output_grid = np.array(example['output'], dtype=np.int32)
                    yield output_grid

class SyntheticDataLoader(BaseDataLoader):
    """Data loader for GAN-generated synthetic grids."""
    def _get_data_generator(self):
        """Loads grids from multiple synthetic dataset JSON files."""
        for path in self.config.synthetic_data_paths:
            try:
                with open(path, 'r') as f:
                    data = json.load(f)
                    logging.info(f"Loading synthetic data from {path}")
                    for item in data:
                        if isinstance(item, list) and all(isinstance(sublist, list) for sublist in item):
                            # Assume it's a list of lists (2D grid)
                            yield np.array(item, dtype=np.int32)
                        elif isinstance(item, list) and all(isinstance(val, (int, float)) for val in item):
                            # Assume it's a flattened list, try to reshape to a square
                            grid_size = int(np.sqrt(len(item)))
                            if grid_size * grid_size == len(item):
                                yield np.array(item, dtype=np.int32).reshape(grid_size, grid_size)
                            else:
                                logging.warning(f"Skipping malformed flattened grid in {path} due to non-square length: {len(item)}")
                        else:
                            logging.warning(f"Skipping malformed data item in {path}: {type(item)}")
            except (FileNotFoundError, json.JSONDecodeError) as e:
                logging.warning(f"Skipping file {path} due to error: {e}")
            except Exception as e:
                logging.error(f"An unexpected error occurred while loading {path}: {e}")

class Sampling(layers.Layer):
    """Uses (z_mean, z_log_var) to sample z, the vector encoding a digit."""
    def call(self, inputs):
        z_mean, z_log_var = inputs
        batch = tf.shape(z_mean)[0]
        dim = tf.shape(z_mean)[1]
        epsilon = tf.random.normal(shape=(batch, dim))
        return z_mean + tf.exp(0.5 * z_log_var) * epsilon

class Encoder(Model):
    """The encoder component of the D-VAE, refactored to use the subclassed API."""
    def __init__(self, latent_dim, grid_size, name='encoder', **kwargs):
        super(Encoder, self).__init__(name=name, **kwargs)
        self.latent_dim = latent_dim
        self.grid_size = grid_size
        self.conv1 = layers.Conv2D(32, 3, activation='relu', strides=2, padding='same', kernel_initializer=GlorotNormal())
        self.bn1 = layers.BatchNormalization()
        self.conv2 = layers.Conv2D(64, 3, activation='relu', strides=2, padding='same', kernel_initializer=GlorotNormal())
        self.bn2 = layers.BatchNormalization()
        # Calculate the expected shape after conv layers
        initial_h = tf.math.ceil(grid_size / 2.0)
        initial_h = tf.cast(tf.math.ceil(initial_h / 2.0), dtype=tf.int32)
        initial_w = tf.math.ceil(grid_size / 2.0)
        initial_w = tf.cast(tf.math.ceil(initial_w / 2.0), dtype=tf.int32)
        self.reshape_before_flatten = layers.Reshape((initial_h * initial_w * 64,)) # Reshape to a fixed size before flatten
        self.flatten = layers.Flatten()
        self.z_mean_dense = layers.Dense(self.latent_dim, name='z_mean')
        self.z_log_var_dense = layers.Dense(self.latent_dim, name='z_log_var')

    def call(self, inputs, training=None):
        x = self.conv1(inputs)
        x = self.bn1(x, training=training) # Pass training argument
        x = self.conv2(x)
        x = self.bn2(x, training=training) # Pass training argument
        x = self.reshape_before_flatten(x) # Apply reshape
        x = self.flatten(x) # Flatten is now redundant but kept for clarity in flow
        z_mean = self.z_mean_dense(x)
        z_log_var = self.z_log_var_dense(x)
        return z_mean, z_log_var

class Decoder(Model):
    """The decoder component of the D-VAE, refactored to use the subclassed API."""
    def __init__(self, latent_dim, num_colors, grid_size, name='decoder', **kwargs):
        super(Decoder, self).__init__(name=name, **kwargs)
        self.num_colors = num_colors
        self.latent_dim = latent_dim
        self.grid_size = grid_size
        initial_h = grid_size // 4
        initial_w = grid_size // 4
        self.dense = layers.Dense(initial_h * initial_w * 16, activation='relu')
        self.reshape = layers.Reshape((initial_h, initial_w, 16))
        self.conv_t1 = layers.Conv2DTranspose(64, 3, activation='relu', strides=2, padding='same', kernel_initializer=GlorotNormal())
        self.bn1 = layers.BatchNormalization()
        self.conv_t2 = layers.Conv2DTranspose(32, 3, activation='relu', strides=2, padding='same', kernel_initializer=GlorotNormal())
        self.bn2 = layers.BatchNormalization()
        self.output_conv = layers.Conv2DTranspose(self.num_colors, 3, activation='softmax', padding='same', kernel_initializer=GlorotNormal())
    def call(self, inputs):
        x = self.dense(inputs)
        x = self.reshape(x)
        x = self.conv_t1(x)
        x = self.bn1(x)
        x = self.conv_t2(x)
        x = self.bn2(x)
        outputs = self.output_conv(x)
        return outputs

class DVAE(Model):
    """The complete VAE model, with encoder and decoder."""
    def __init__(self, latent_dim, num_colors, grid_size, **kwargs):
        super(DVAE, self).__init__(**kwargs)
        self.latent_dim = latent_dim
        self.num_colors = num_colors
        self.grid_size = grid_size
        # Explicitly define input shape for encoder and decoder
        encoder_input_shape = (grid_size, grid_size, 1) # Assuming single channel input
        decoder_input_shape = (latent_dim,)
        self.encoder = Encoder(latent_dim=latent_dim, grid_size=grid_size)
        # Removed explicit build call for encoder
        self.decoder = Decoder(latent_dim=latent_dim, num_colors=num_colors, grid_size=grid_size)
        # Removed explicit build call for decoder
        self.sampling = Sampling()

    def call(self, inputs):
        inputs_f32 = tf.cast(inputs, dtype=tf.float32)
        z_mean, z_log_var = self.encoder(inputs_f32)
        z = self.sampling([z_mean, z_log_var])
        reconstruction = self.decoder(z)
        kl_loss = -0.5 * tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1)
        self.add_loss(tf.reduce_mean(kl_loss))
        return reconstruction

class ModelTrainer:
    """Handles the compilation and training of the VAE model."""
    def __init__(self, config, model, dataset):
        self.config = config
        self.model = model
        self.dataset = dataset
        self.checkpoint_path = os.path.join(self.config.vae_checkpoints_dir, 'dvae_checkpoint.weights.h5')
    def train(self):
        logging.info("Compiling VAE model...")
        optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
        self.model.compile(optimizer=optimizer, loss=SparseCategoricalCrossentropy(from_logits=False), run_eagerly=False)
        logging.info("Starting VAE training...")
        callbacks = [
            ModelCheckpoint(self.checkpoint_path, save_best_only=True, save_weights_only=True),
            TensorBoard(log_dir=os.path.join(self.config.project_root, 'logs')),
            tf.keras.callbacks.EarlyStopping(monitor='loss', patience=3)
        ]
        self.model.fit(
            self.dataset,
            epochs=self.config.epochs,
            callbacks=callbacks
        )
        self.model.save_weights(self.checkpoint_path)
        logging.info(f"D-VAE model weights saved to {self.checkpoint_path}")

class PlausibilityValidator:
    """Uses the trained VAE to score the plausibility of an ARC grid."""
    def __init__(self, vae_model):
        self.vae_model = vae_model
        self.loss_fn = SparseCategoricalCrossentropy(from_logits=False)
    def get_plausibility_score(self, grid):
        """Calculates a plausibility score based on VAE's reconstruction error."""
        # Ensure input grid is int32 and add batch and channel dimensions for VAE input
        grid_tensor_input = tf.cast(tf.expand_dims(tf.expand_dims(grid, axis=0), axis=-1), dtype=tf.float32)
        reconstruction = self.vae_model(grid_tensor_input, training=False)

        # Prepare the target grid for loss calculation
        # Cast to int32, add batch dimension, and remove the extra channel dimension
        grid_tensor_loss_target = tf.cast(tf.expand_dims(grid, axis=0), dtype=tf.int32) # Shape (1, grid_size, grid_size)

        # Ensure shapes for robustness (optional, but good practice after manipulation)
        # reconstruction = tf.ensure_shape(reconstruction, (1, self.vae_model.grid_size, self.vae_model.grid_size, self.vae_model.num_colors))
        # grid_tensor_loss_target = tf.ensure_shape(grid_tensor_loss_target, (1, self.vae_model.grid_size, self.vae_model.grid_size))

        reconstruction_loss = self.loss_fn(grid_tensor_loss_target, reconstruction)
        return tf.exp(-reconstruction_loss).numpy()

class RLAgent:
    """
    A Reinforcement Learning agent using a Deep Q-Network (DQN) to generate
    plausible ARC grids based on feedback from a trained VAE.
    """
    def __init__(self, vae_model, grid_size, num_colors, learning_rate=0.001,
                 discount_factor=0.99, exploration_rate=1.0, min_exploration_rate=0.01,
                 exploration_decay_rate=0.995):
        self.vae_model = vae_model
        self.grid_size = grid_size
        self.num_colors = num_colors
        self.action_space_size = grid_size * grid_size * num_colors
        self.learning_rate = learning_rate
        self.discount_factor = discount_factor
        self.exploration_rate = exploration_rate
        self.min_exploration_rate = min_exploration_rate
        self.exploration_decay_rate = exploration_decay_rate
        self.q_network = self._build_q_network()
        self.optimizer = Adam(learning_rate=self.learning_rate)
    def _build_q_network(self):
        inputs = layers.Input(shape=(self.grid_size, self.grid_size, 1), dtype=tf.float32)
        x = layers.Conv2D(32, 3, activation='relu', padding='same')(inputs)
        x = layers.Flatten()(x)
        x = layers.Dense(128, activation='relu')(x)
        outputs = layers.Dense(self.action_space_size)(x)
        return Model(inputs=inputs, outputs=outputs)
    def choose_action(self, state_grid):
        if np.random.uniform(0, 1) < self.exploration_rate:
            action_index = np.random.randint(self.action_space_size)
        else:
            state_tensor = tf.cast(tf.expand_dims(tf.expand_dims(state_grid, 0), -1), dtype=tf.float32)
            q_values = self.q_network(state_tensor, training=False)
            action_index = tf.argmax(q_values[0]).numpy()
        return self._map_index_to_action(action_index)
    def _map_index_to_action(self, index):
        color = index % self.num_colors
        index = index // self.num_colors
        y = index % self.grid_size
        x = index // self.grid_size
        return (x, y, color)
    def _map_action_to_index(self, x, y, color):
        return x * self.grid_size * self.num_colors + y * self.num_colors + color
    def train_step(self, state, action, reward, next_state, done):
        state_tensor = tf.cast(tf.expand_dims(tf.expand_dims(state, 0), -1), dtype=tf.float32)
        next_state_tensor = tf.cast(tf.expand_dims(tf.expand_dims(next_state, 0), -1), dtype=tf.float32)
        with tf.GradientTape() as tape:
            q_values = self.q_network(state_tensor)
            if done:
                target_q_value = reward
            else:
                next_q_values = self.q_network(next_state_tensor)
                max_next_q_value = tf.reduce_max(next_q_values)
                target_q_value = reward + self.discount_factor * max_next_q_value
            action_mask = tf.one_hot(self._map_action_to_index(*action), self.action_space_size, dtype=tf.float32)
            q_value_for_action = tf.reduce_sum(q_values * action_mask, axis=1)
            loss = tf.keras.losses.MSE(tf.expand_dims(target_q_value, 0), q_value_for_action)
        grads = tape.gradient(loss, self.q_network.trainable_variables)
        self.optimizer.apply_gradients(zip(grads, self.q_network.trainable_variables))
    def get_vae_reward(self, grid):
        plausibility_validator = self.vae_model
        loss = -plausibility_validator.get_plausibility_score(grid)
        return float(loss)
    def decay_exploration_rate(self):
        self.exploration_rate = max(self.min_exploration_rate, self.exploration_rate * self.exploration_decay_rate)
    def generate_grid_with_rl(self, max_steps=1000):
        current_grid = np.zeros((self.grid_size, self.grid_size), dtype=np.int32)
        for step in range(max_steps):
            action = self.choose_action(current_grid)
            x, y, color = action
            next_grid = current_grid.copy()
            next_grid[x, y] = color
            reward = self.get_vae_reward(next_grid)
            done = step == max_steps - 1
            self.train_step(current_grid, action, reward, next_grid, done)
            current_grid = next_grid
        return current_grid

# -----------------------------------------------------------------------------
# -- Main Pipeline Orchestrator (The "Base Route File" Logic)
# -----------------------------------------------------------------------------
def main():
    """
    Orchestrates the data loading, model training, and validation demonstration.
    This function serves as the central "route" for the pipeline.
    """
    logging.info("Initializing ARC AGI Project...")
    mount_google_drive()

    # 1. Configuration
    config = ARCConfig()
    os.makedirs(config.vae_checkpoints_dir, exist_ok=True)

    # 2. Data Preparation Route
    logging.info("Loading and preparing data...")
    arc_data_loader = ARCDataLoader(config)
    synthetic_data_loader = SyntheticDataLoader(config)
    arc_ds = arc_data_loader.load_dataset()
    synthetic_ds = synthetic_data_loader.load_dataset()
    combined_ds = arc_ds.concatenate(synthetic_ds)

    # 3. VAE Model Training Route
    logging.info("Building VAE model...")
    vae = DVAE(latent_dim=config.latent_dim, num_colors=config.num_colors, grid_size=config.grid_size)
    vae.build(input_shape=(None, config.grid_size, config.grid_size, 1))
    trainer = ModelTrainer(config, vae, combined_ds)
    trainer.train()

    # 4. Plausibility Validator Route
    logging.info("\nDemonstrating Plausibility Validator...")
    validator = PlausibilityValidator(vae)
    plausible_grid = np.zeros((config.grid_size, config.grid_size), dtype=np.int32)
    plausible_grid[5:10, 5:10] = 1
    plausibility_score_1 = validator.get_plausibility_score(plausible_grid)
    logging.info(f"Plausibility score for a simple square grid: {plausibility_score_1:.4f}")

    # Example 2: Implausible grid (random noise)
    implausible_grid = np.random.randint(0, config.num_colors, size=(config.grid_size, config.grid_size), dtype=np.int32)
    plausibility_score_2 = validator.get_plausibility_score(implausible_grid)
    logging.info(f"Plausibility score for a random noise grid: {plausibility_score_2:.4f}")

    # 5. RL Agent Route (Placeholder for the next step in the pipeline)
    logging.info("\nDemonstrating RL Agent (placeholder)...")
    # Here you would instantiate and train the RL agent.
    # rl_agent = RLAgent(vae_model=vae, grid_size=config.grid_size, num_colors=config.num_colors)
    # generated_grid = rl_agent.generate_grid_with_rl()
    # logging.info("Generated a grid using the RL agent.")

if __name__ == "__main__":
    main()









