# -*- coding: utf-8 -*-
"""Copy of ARC-AGI 2025: Visualization all 1000+120 tasks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKa16hBHL2O1myQ1pDG_ylLS1PoM6I9q
"""

from google.colab import drive
drive.mount('/content/drive')

"""<center>
<img src="https://i.postimg.cc/x8dWTCX3/1234-Untitled.png" width=1100>
</center>

# <div  style="color:white; border:lightgreen solid;  font-weight:bold; font-size:120%; text-align:center;padding:12.0px; background:black">1. DATA LOADING AND PREPARATION</div>

## Import libraries and define parameters
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from   matplotlib import colors
import seaborn as sns

import json
import os
import glob
from pathlib import Path

"""Loading JSON data:"""

base_path='/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data'

def load_json(file_path):
    with open(file_path) as f:
        data = json.load(f)
    return data



"""Reading files:"""

#training_challenges   = load_json(base_path +'arc-agi_training_challenges.json')
#training_solutions    = load_json(base_path +'arc-agi_training_solutions.json')

#evaluation_challenges = load_json(base_path +'arc-agi_evaluation_challenges.json')
#evaluation_solutions  = load_json(base_path +'arc-agi_evaluation_solutions.json')

"""### Function to plot input/output pairs of a task"""

# 0:black, 1:blue, 2:red, 3:green, 4:yellow, # 5:gray, 6:magenta, 7:orange, 8:sky, 9:brown

cmap = colors.ListedColormap(
    ['#000000', '#0074D9', '#FF4136', '#2ECC40', '#FFDC00',
     '#AAAAAA', '#F012BE', '#FF851B', '#7FDBFF', '#870C25'])
norm = colors.Normalize(vmin=0, vmax=9)

plt.figure(figsize=(3, 1), dpi=150)
plt.imshow([list(range(10))], cmap=cmap, norm=norm)
plt.xticks(list(range(10)))
plt.yticks([])
plt.tick_params(axis='x', color='r', length=0, grid_color='none')

plt.show()

def plot_task(task, task_solutions, i, t, size=2.5, w1=0.9):
    t=list(training_challenges)[i]
    titleSize=16
    num_train = len(task['train'])
    num_test  = len(task['test'])

    wn=num_train+num_test
    fig, axs  = plt.subplots(2, wn, figsize=(size*wn,2*size))
    plt.suptitle(f'Task #{i}, {t}', fontsize=titleSize, fontweight='bold', y=1, color = '#eeeeee')

    '''train:'''
    for j in range(num_train):
        plot_one(axs[0, j], j,task, 'train', 'input',  w=w1)
        plot_one(axs[1, j], j,task, 'train', 'output', w=w1)

    '''test:'''
    for k in range(num_test):
        plot_one(axs[0, j+k+1], k, task, 'test', 'input', w=w1)
        task['test'][k]['output'] = task_solutions[k]
        plot_one(axs[1, j+k+1], k, task, 'test', 'output', w=w1)

    axs[1, j+1].set_xticklabels([])
    axs[1, j+1].set_yticklabels([])
    axs[1, j+1] = plt.figure(1).add_subplot(111)
    axs[1, j+1].set_xlim([0, wn])

    '''Separators:'''
    colorSeparator = 'white'
    for m in range(1, wn):
        axs[1, j+1].plot([m,m],[0,1],'--', linewidth=1, color = colorSeparator)
    axs[1, j+1].plot([num_train,num_train],[0,1],'-', linewidth=3, color = colorSeparator)

    axs[1, j+1].axis("off")

    '''Frame and background:'''
    fig.patch.set_linewidth(5) #widthframe
    fig.patch.set_edgecolor('black') #colorframe
    fig.patch.set_facecolor('#444444') #background

    plt.tight_layout()

    print(f'#{i}, {t}') # for fast and convinience search
    plt.show()

def plot_one(ax, i, task, train_or_test, input_or_output, solution=None, w=0.8):
    fs=12
    input_matrix = task[train_or_test][i][input_or_output]
    ax.imshow(input_matrix, cmap=cmap, norm=norm)

    #ax.grid(True, which = 'both',color = 'lightgrey', linewidth = 1.0)
    plt.setp(plt.gcf().get_axes(), xticklabels=[], yticklabels=[])
    ax.set_xticks([x-0.5 for x in range(1 + len(input_matrix[0]))])
    ax.set_yticks([x-0.5 for x in range(1 + len(input_matrix))])

    '''Grid:'''
    ax.grid(visible= True, which = 'both', color = '#666666', linewidth = w)

    ax.tick_params(axis='both', color='none', length=0)

    '''sub title:'''
    ax.set_title(train_or_test + ' ' + input_or_output, fontsize=fs, color = '#dddddd')

"""# <div  style="color:white; border:lightgreen solid;  font-weight:bold; font-size:120%; text-align:center;padding:12.0px; background:black">2. VISUALIZATION TRAINING SET</div>

## 000-100 tasks

for i in range(0, 100):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)
    "

## 100-200 tasks

for i in range(100, 200):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 200-300 tasks

for i in range(200, 300):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 300-400 tasks

for i in range(300, 400):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 400-500 tasks

for i in range(400, 500):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 500-600 tasks

for i in range(500, 600):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 600-700 tasks

for i in range(600, 700):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 700-800 tasks

for i in range(700, 800):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 800-900 tasks

for i in range(800, 900):
    t=list(training_challenges)[i]
    task=training_challenges[t]
    task_solution = training_solutions[t]
    plot_task(task,  task_solution, i, t)

## 900-1000 tasks

for i in range(900, 1000):
    if i not in []:
        t=list(training_challenges)[i]
        task=training_challenges[t]
        task_solution = training_solutions[t]
        plot_task(task,  task_solution, i, t)

# <div  style="color:white; border:lightgreen solid;  font-weight:bold; font-size:120%; text-align:center;padding:12.0px; background:black">2. VISUALIZATION EVALUATION SET</div>

## 000-120 tasks

for i in range(0, 120):
    t=list(evaluation_challenges)[i]
    task=evaluation_challenges[t]
    task_solution = evaluation_solutions[t]
    plot_task(task,  task_solution, i, t)
"""

class GridTransformer:
    """
    A class to apply 8 unique geometric transformations to grids.
    The transformations are: rotations (0, 90, 180, 270 degrees) and mirroring (horizontal, vertical, main diagonal, anti-diagonal).
    """
    @staticmethod
    def rotate_90(grid):
        """Rotates a grid 90 degrees clockwise."""
        return [list(row) for row in zip(*grid[::-1])]

    @staticmethod
    def rotate_180(grid):
        """Rotates a grid 180 degrees."""
        return [row[::-1] for row in grid[::-1]]

    @staticmethod
    def rotate_270(grid):
        """Rotates a grid 270 degrees clockwise."""
        return [list(row) for row in zip(*grid)][::-1]

    @staticmethod
    def flip_horizontal(grid):
        """Flips a grid horizontally."""
        return [row[::-1] for row in grid]

    @staticmethod
    def flip_vertical(grid):
        """Flips a grid vertically."""
        return grid[::-1]

    @staticmethod
    def flip_main_diagonal(grid):
        """Flips a grid along its main diagonal."""
        return [list(row) for row in zip(*grid)]

    @staticmethod
    def flip_anti_diagonal(grid):
        """Flips a grid along its anti-diagonal."""
        rotated_grid = GridTransformer.rotate_90(grid)
        return GridTransformer.flip_horizontal(rotated_grid)

    def get_all_transformations(self, grid):
        """
        Applies all 8 transformations to a grid and returns them in a dictionary.
        Returns:
            A dictionary with transformation names as keys and the transformed grids as values.
        """
        transformations = {
            "Original": grid,
            "Rotated_90_deg": self.rotate_90(grid),
            "Rotated_180_deg": self.rotate_180(grid),
            "Rotated_270_deg": self.rotate_270(grid),
            "Flipped_Horizontally": self.flip_horizontal(grid),
            "Flipped_Vertically": self.flip_vertical(grid),
            "Flipped_Main_Diagonal": self.flip_main_diagonal(grid),
            "Flipped_Anti-Diagonal": self.flip_anti_diagonal(grid)
        }
        return transformations

class DataSaver:
    """
    A class to save data to a JSON file.
    """
    def save_to_json(self, data, file_path, indent=4):
        """Saves a Python dictionary to a JSON file."""
        try:
            with open(file_path, 'w') as f:
                json.dump(data, f, indent=indent)
            print(f"Data successfully saved to: {file_path}")
        except Exception as e:
            print(f"Error saving data: {e}")

def plot_grids(title, input_grid, output_grid):
    """Plots input and output grids with their corresponding title."""
    fig, axs = plt.subplots(1, 2, figsize=(5, 2.5))
    fig.suptitle(title, fontsize=12, fontweight='bold', color='#eeeeee', y=1.05)

    axs[0].imshow(input_grid, cmap=cmap, norm=norm)
    axs[0].set_title('Input', color='#dddddd')
    axs[0].set_xticks(np.arange(-.5, len(input_grid[0]), 1))
    axs[0].set_yticks(np.arange(-.5, len(input_grid), 1))
    axs[0].set_xticklabels([])
    axs[0].set_yticklabels([])
    axs[0].grid(visible=True, color='#666666', linewidth=0.8)

    axs[1].imshow(output_grid, cmap=cmap, norm=norm)
    axs[1].set_title('Output', color='#dddddd')
    axs[1].set_xticks(np.arange(-.5, len(output_grid[0]), 1))
    axs[1].set_yticks(np.arange(-.5, len(output_grid), 1))
    axs[1].set_xticklabels([])
    axs[1].set_yticklabels([])
    axs[1].grid(visible=True, color='#666666', linewidth=0.8)

    fig.patch.set_facecolor('#444444')
    plt.tight_layout()
    plt.show()

def process_and_save_all_transformations(file_path, base_output_dir):
    """
    Loads and processes tasks from a given dataset file, applies all 8 geometric
    transformations, and saves the results to a specified output directory.
    """
    transformer = GridTransformer()
    data_saver = DataSaver()

    try:
        challenges = load_json(file_path)
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return
    except json.JSONDecodeError:
        print(f"Error decoding JSON from file: {file_path}")
        return

    task_keys = list(challenges.keys())

    print(f"\nProcessing tasks from {file_path}:")

    # Define the 8 transformation method names for folder creation
    transformation_methods = [
        "Rotated_90_deg", "Rotated_180_deg", "Rotated_270_deg",
        "Flipped_Horizontally", "Flipped_Vertically", "Flipped_Main_Diagonal",
        "Flipped_Anti-Diagonal", "Original"
    ]

    for task_id in task_keys:
        # Check if 'train' exists and has at least one example
        if 'train' not in challenges[task_id] or not challenges[task_id]['train']:
            continue

        # We process each task here
        task_data = challenges[task_id]['train'][0]
        input_grid = task_data['input']

        # The output grid might be missing for some challenges, we handle that.
        output_grid = task_data.get('output', [])

        print(f"\n--- Processing Task ID: {task_id} ---")

        # Apply transformations to both input and output grids
        transformed_input_data = transformer.get_all_transformations(input_grid)
        transformed_output_data = transformer.get_all_transformations(output_grid)

        # Plot the original grids for verification
        # plot_grids(f'Original Grids (Task ID: {task_id})', input_grid, output_grid)

        # Save each transformation to its own directory
        for method in transformation_methods:
            # Create the output directory for the specific transformation method
            output_dir = Path(base_output_dir) / method
            output_dir.mkdir(parents=True, exist_ok=True)

            # Combine the transformed data into a single dictionary
            transformed_data = {
                'task_id': task_id,
                'input': transformed_input_data[method],
                'output': transformed_output_data[method]
            }

            # Define the output file path and save the data
            output_file_path = output_dir / f'transformed_{task_id}.json'
            data_saver.save_to_json(transformed_data, output_file_path)


if __name__ == '__main__':
    base_data_path = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data'

    # Process all challenge files in the 'training' directory
    training_challenge_files = glob.glob(f"{base_data_path}/training/*.json")
    for file_path in training_challenge_files:
        output_dir_path = os.path.join(base_data_path, 'training_transformed')
        process_and_save_all_transformations(file_path, output_dir_path)

    # Process all challenge files in the 'evaluation' directory
    evaluation_challenge_files = glob.glob(f"{base_data_path}/evaluation/*.json")
    for file_path in evaluation_challenge_files:
        output_dir_path = os.path.join(base_data_path, 'evaluation_transformed')

