# -*- coding: utf-8 -*-
"""GAN Trainer with Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--9Ee1V8_JxHkD_AaJX5x3G2-CPRvGO0
"""



from google.colab import drive
drive.mount('/content/drive')

import os
import json
import glob
from pathlib import Path
from tqdm import tqdm
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import KFold
import math
import random
import matplotlib.pyplot as plt
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.cuda.amp import autocast, GradScaler

# --- 1. CONFIGURATION ---
CONFIG = {
    # Data Paths
    'base_data_path': '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data',
    'input_directory': 'GridTransitionDataset/training_transformed_unique_ids',
    'output_directory': '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/models2',

    # Model Hyperparameters
    'vocab_size': 12,
    'max_seq_len': 1802,
    'd_model': 128,         # Increased model dimension
    'nhead': 4,
    'num_layers': 4,        # Increased number of layers
    'dim_feedforward': 512, # Increased feedforward dimension
    'dropout': 0.1,

    # Training Parameters
    'batch_size': 32,
    'learning_rate': 0.0002,
    'num_epochs': 10,       # Increased epochs for the larger model
    'n_splits': 5,
    'train_generator_every': 1,
    'label_smoothing': 0.1, # Added label smoothing parameter
    'gradient_clipping_value': 1.0, # Added gradient clipping parameter
    'gradient_accumulation_steps': 4 # Added gradient accumulation steps
}

# --- 2. DATASET CLASS ---
class ARCDataset(Dataset):
    def __init__(self, sequences):
        self.sequences = sequences

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        return self.sequences[idx]

# --- 3. MODEL ARCHITECTURE ---
class Generator(nn.Module):
    def __init__(self, vocab_size, d_model, nhead, num_layers, dim_feedforward, dropout):
        super().__init__()
        # Embedding layer to convert discrete tokens to vectors
        self.token_embedding = nn.Embedding(vocab_size, d_model)
        # Transformer Encoder to process the embedded sequence
        encoder_layer = nn.TransformerEncoderLayer(d_model, nhead, dim_feedforward, dropout, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers)
        # Output layer to convert back to token logits
        self.output_layer = nn.Linear(d_model, vocab_size)

    def forward(self, src):
        # src is expected to be a LongTensor of token indices
        src = self.token_embedding(src)
        output = self.transformer_encoder(src)
        logits = self.output_layer(output)
        return logits

class Discriminator(nn.Module):
    def __init__(self, vocab_size, d_model, nhead, num_layers, dim_feedforward, dropout):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, d_model)
        encoder_layer = nn.TransformerEncoderLayer(d_model, nhead, dim_feedforward, dropout, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers)
        self.output_layer = nn.Linear(d_model, 1)

    def forward(self, src):
        src = self.token_embedding(src)
        output = self.transformer_encoder(src)
        # Global average pooling over the sequence dimension
        output = torch.mean(output, dim=1)
        return self.output_layer(output)

# --- 4. WEIGHTS INITIALIZATION ---
def weights_init(m):
    """Initializes weights using Xavier uniform distribution."""
    if isinstance(m, nn.Linear):
        nn.init.xavier_uniform_(m.weight)
        if m.bias is not None:
            nn.init.constant_(m.bias, 0)
    elif isinstance(m, nn.Embedding):
        nn.init.xavier_uniform_(m.weight)

# --- 5. TRAINER CLASS ---
class GANTrainer:
    def __init__(self, config):
        self.config = config
        self.device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        os.makedirs(self.config['output_directory'], exist_ok=True)

        print("--- Pre-loading and Caching All Data ---")
        all_file_paths = glob.iglob(
            os.path.join(self.config['base_data_path'], self.config['input_directory'], '**', '*.json'),
            recursive=True
        )
        self.all_sequences = self._load_all_sequences(list(all_file_paths))
        print(f"Total sequences loaded: {len(self.all_sequences)}")

        # Initialize final_generator to None
        self.final_generator = None

    def _load_all_sequences(self, file_paths):
        """Loads and processes all valid sequences from JSON files."""
        all_sequences = []
        skipped_files = 0
        for file_path in tqdm(file_paths, desc="Loading and Caching Data"):
            try:
                with open(file_path, 'r') as f:
                    task = json.load(f)
                    # Check if 'train' key exists and is not empty
                    if 'train' in task and isinstance(task['train'], list) and task['train']:
                        for example in task['train']:
                            # Check if 'input' and 'output' keys exist and are not empty
                            if 'input' in example and example['input'] and 'output' in example and example['output']:
                                input_grid = np.array(example['input'])
                                output_grid = np.array(example['output'])

                                # Flatten and concatenate the grids
                                start_token, sep_token, pad_token = 10, 11, 0
                                input_flat = input_grid.flatten()
                                output_flat = output_grid.flatten()

                                sequence = np.concatenate([
                                    [start_token],
                                    input_flat,
                                    [sep_token],
                                    output_flat
                                ])

                                # Pad sequence to max length
                                if len(sequence) > CONFIG['max_seq_len']:
                                    sequence = sequence[:CONFIG['max_seq_len']]

                                padded_sequence = np.pad(sequence, (0, CONFIG['max_seq_len'] - len(sequence)), 'constant', constant_values=pad_token)
                                all_sequences.append(torch.tensor(padded_sequence, dtype=torch.long))
                            else:
                                skipped_files += 1
                                continue
                    else:
                        skipped_files += 1
                        continue
            except json.JSONDecodeError:
                print(f"Error decoding JSON from file: {file_path}")
                skipped_files += 1
                continue
            except Exception as e:
                print(f"Error processing file {file_path}: {e}")
                skipped_files += 1
                continue
        if skipped_files > 0:
            print(f"Skipped {skipped_files} files due to invalid format.")
        return all_sequences

    def run_cross_validation(self):
        """Runs the K-Fold cross-validation training process."""
        k_fold = KFold(n_splits=self.config['n_splits'], shuffle=True, random_state=42)

        fold_discriminator_losses = []
        fold_generator_losses = []

        if len(self.all_sequences) == 0:
            print("No sequences loaded. Cannot perform cross-validation.")
            return

        for fold, (train_ids, val_ids) in enumerate(k_fold.split(self.all_sequences)):
            print(f"--- FOLD {fold+1}/{self.config['n_splits']} ---")

            generator = Generator(
                self.config['vocab_size'], self.config['d_model'], self.config['nhead'],
                self.config['num_layers'], self.config['dim_feedforward'], self.config['dropout']
            ).to(self.device)
            discriminator = Discriminator(
                self.config['vocab_size'], self.config['d_model'], self.config['nhead'],
                self.config['num_layers'], self.config['dim_feedforward'], self.config['dropout']
            ).to(self.device)

            generator.apply(weights_init)
            discriminator.apply(weights_init)

            optimizer_G = optim.AdamW(generator.parameters(), lr=self.config['learning_rate'])
            optimizer_D = optim.AdamW(discriminator.parameters(), lr=self.config['learning_rate'])
            criterion = nn.BCEWithLogitsLoss()

            scheduler_G = CosineAnnealingLR(optimizer_G, T_max=self.config['num_epochs'])
            scheduler_D = CosineAnnealingLR(optimizer_D, T_max=self.config['num_epochs'])

            scaler = GradScaler()

            train_subsampler = torch.utils.data.SubsetRandomSampler(train_ids)
            dataset = ARCDataset(self.all_sequences)
            train_loader = DataLoader(dataset, batch_size=self.config['batch_size'], sampler=train_subsampler)

            avg_fold_disc_loss, avg_fold_gen_loss = self.train_gan(
                generator, discriminator, optimizer_G, optimizer_D, criterion, train_loader,
                scheduler_G, scheduler_D, scaler
            )

            fold_discriminator_losses.append(avg_fold_disc_loss)
            fold_generator_losses.append(avg_fold_gen_loss)

            self.save_models(generator, discriminator, fold + 1)

        print("\n--- Cross-Validation Results ---")
        avg_disc_loss_cv = sum(fold_discriminator_losses) / self.config['n_splits']
        avg_gen_loss_cv = sum(fold_generator_losses) / self.config['n_splits']
        print(f"Average Discriminator Loss across {self.config['n_splits']} folds: {avg_disc_loss_cv:.4f}")
        print(f"Average Generator Loss across {self.config['n_splits']} folds: {avg_gen_loss_cv:.4f}")
        self.save_results(fold_discriminator_losses, fold_generator_losses, avg_disc_loss_cv, avg_gen_loss_cv)

        # Save the final generator for visualization
        self.final_generator = generator

    def train_gan(self, generator, discriminator, optimizer_G, optimizer_D, criterion, data_loader, scheduler_G, scheduler_D, scaler):
        """Trains the GAN for one fold."""
        fold_disc_losses_epoch = []
        fold_gen_losses_epoch = []
        gen_updates = 0
        disc_updates = 0

        for epoch in range(self.config['num_epochs']):
            d_loss_total = 0
            g_loss_total = 0

            for i, real_sequences in enumerate(tqdm(data_loader, desc=f"Epoch {epoch+1}/{self.config['num_epochs']}")):
                real_sequences = real_sequences.to(self.device)
                batch_size = real_sequences.size(0)

                # Use label smoothing for real labels
                smooth_real_labels = torch.full((batch_size, 1), 1.0 - self.config['label_smoothing'], device=self.device)
                smooth_fake_labels = torch.full((batch_size, 1), self.config['label_smoothing'], device=self.device)

                # --- Train Discriminator ---
                discriminator.zero_grad()
                with autocast():
                    # Train with real data
                    d_output_real = discriminator(real_sequences)
                    d_loss_real = criterion(d_output_real, smooth_real_labels)

                    # Train with fake data
                    fake_input_indices = torch.randint(0, self.config['vocab_size'], (batch_size, self.config['max_seq_len']), dtype=torch.long, device=self.device)
                    fake_sequences_logits = generator(fake_input_indices)

                    # Gumbel-Softmax for differentiable sampling
                    fake_sequences_gumbel = F.gumbel_softmax(fake_sequences_logits, tau=0.5, hard=True, dim=-1)
                    # Convert one-hot to discrete indices for the discriminator
                    fake_sequences = torch.argmax(fake_sequences_gumbel, dim=-1)

                    d_output_fake = discriminator(fake_sequences.detach()) # Detach to prevent gradients from flowing to generator
                    d_loss_fake = criterion(d_output_fake, smooth_fake_labels)

                    d_loss = d_loss_real + d_loss_fake

                scaler.scale(d_loss).backward()
                disc_updates += 1

                if disc_updates % self.config['gradient_accumulation_steps'] == 0:
                    scaler.unscale_(optimizer_D)
                    torch.nn.utils.clip_grad_norm_(discriminator.parameters(), self.config['gradient_clipping_value'])
                    scaler.step(optimizer_D)
                    scaler.update()
                    discriminator.zero_grad()

                d_loss_total += d_loss.item()

                # --- Train Generator ---
                if i % self.config['train_generator_every'] == 0:
                    generator.zero_grad()
                    gen_labels = torch.ones(batch_size, 1, device=self.device)

                    with autocast():
                        fake_input_indices_gen = torch.randint(0, self.config['vocab_size'], (batch_size, self.config['max_seq_len']), dtype=torch.long, device=self.device)
                        fake_sequences_logits_gen = generator(fake_input_indices_gen)

                        fake_sequences_gen_gumbel = F.gumbel_softmax(fake_sequences_logits_gen, tau=0.5, hard=True, dim=-1)
                        fake_sequences_gen = torch.argmax(fake_sequences_gen_gumbel, dim=-1)

                        g_output = discriminator(fake_sequences_gen)
                        g_loss = criterion(g_output, gen_labels)

                    scaler.scale(g_loss).backward()
                    gen_updates += 1

                    if gen_updates % self.config['gradient_accumulation_steps'] == 0:
                        scaler.unscale_(optimizer_G)
                        torch.nn.utils.clip_grad_norm_(generator.parameters(), self.config['gradient_clipping_value'])
                        scaler.step(optimizer_G)
                        scaler.update()
                        generator.zero_grad()

                    g_loss_total += g_loss.item()

            scheduler_G.step()
            scheduler_D.step()

            fold_disc_losses_epoch.append(d_loss_total / len(data_loader))
            fold_gen_losses_epoch.append(g_loss_total / (len(data_loader) / self.config['train_generator_every']))

        avg_fold_discriminator_loss = sum(fold_disc_losses_epoch) / len(fold_disc_losses_epoch)
        avg_fold_generator_loss = sum(fold_gen_losses_epoch) / len(fold_gen_losses_epoch)

        print(f"--- Finished Fold ---")
        print(f"Average Discriminator Loss: {avg_fold_discriminator_loss:.4f}")
        print(f"Average Generator Loss: {avg_fold_gen_loss:.4f}")

        return avg_fold_discriminator_loss, avg_fold_gen_loss

    def save_models(self, generator, discriminator, fold):
        """Saves the generator and discriminator models."""
        generator_path = os.path.join(self.config['output_directory'], f'generator_fold_{fold}.pth')
        discriminator_path = os.path.join(self.config['output_directory'], f'discriminator_fold_{fold}.pth')
        torch.save(generator.state_dict(), generator_path)
        torch.save(discriminator.state_dict(), discriminator_path)
        print(f"Saved models for fold {fold} to {generator_path} and {discriminator_path}")

    def save_results(self, fold_discriminator_losses, fold_generator_losses, avg_disc_loss_cv, avg_gen_loss_cv):
        """Saves the cross-validation results to a JSON file."""
        results = {
            'fold_discriminator_losses': fold_discriminator_losses,
            'fold_generator_losses': fold_generator_losses,
            'average_discriminator_loss_cv': avg_disc_loss_cv,
            'average_generator_loss_cv': avg_gen_loss_cv,
            'config': self.config
        }
        results_path = os.path.join(self.config['output_directory'], 'cross_validation_results.json')
        with open(results_path, 'w') as f:
            json.dump(results, f, indent=4)
        print(f"Saved cross-validation results to {results_path}")

    def visualize_grid(self, grid_sequence, ax, title):
        """Visualizes a single flattened grid sequence."""
        # Find the separation token to split the input and output grids
        sep_token_index = (grid_sequence == 11).nonzero(as_tuple=True)[0]
        if sep_token_index.numel() > 0:
            sep_index = sep_token_index[0].item()
            # Split into input and output grids (ignoring the start token and sep token)
            output_flat = grid_sequence[sep_index + 1:]

            # Remove padding tokens
            output_flat = output_flat[output_flat != 0]

            # Try to reshape the output into a square grid for visualization
            size = int(np.sqrt(len(output_flat)))
            if size * size == len(output_flat):
                grid = output_flat.view(size, size).cpu().numpy()
                ax.imshow(grid, cmap='tab10', vmin=0, vmax=9)
                ax.set_title(title)
                ax.set_xticks(np.arange(size))
                ax.set_yticks(np.arange(size))
                ax.set_xticklabels([])
                ax.set_yticklabels([])
                ax.grid(which='both', color='gray', linestyle='-', linewidth=0.5)
            else:
                ax.set_title(f"{title}\n(Non-square grid)")
                ax.axis('off')
        else:
            ax.set_title(f"{title}\n(No separator token)")
            ax.axis('off')

    def generate_and_visualize_samples(self, num_samples=16):
        """
        Loads the final trained generator, generates new samples,
        and visualizes them.
        """
        print("\n--- Generating and Visualizing Samples ---")
        if self.final_generator is None:
            print("Generator not trained. Cannot generate samples.")
            return

        self.final_generator.eval()
        with torch.no_grad():
            # Generate a batch of random integer indices for the generator's input
            fake_input_indices = torch.randint(
                0, self.config['vocab_size'],
                (num_samples, self.config['max_seq_len']),
                dtype=torch.long, device=self.device
            )
            fake_sequences_logits = self.final_generator(fake_input_indices)

            # Apply Gumbel-Softmax and argmax to get discrete tokens
            fake_sequences_one_hot = F.gumbel_softmax(fake_sequences_logits, tau=0.5, hard=True, dim=-1)
            generated_sequences = torch.argmax(fake_sequences_one_hot, dim=-1)

        # Visualize the generated sequences
        fig, axes = plt.subplots(int(np.sqrt(num_samples)), int(np.sqrt(num_samples)), figsize=(12, 12))
        axes = axes.flatten()
        for i, ax in enumerate(axes):
            self.visualize_grid(generated_sequences[i], ax, f'Generated Grid {i+1}')

        plt.tight_layout()
        plt.show()

# --- 6. MAIN EXECUTION ---
if __name__ == '__main__':
    trainer = GANTrainer(CONFIG)
    trainer.run_cross_validation()
    trainer.generate_and_visualize_samples()

