# -*- coding: utf-8 -*-
"""SampleTest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVY77Ts0aLv9xDLM5QvNeIfldzyFZBpO
"""

from google.colab import drive
drive.mount('/content/drive')

train_data_set = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids'

#implement GAN -> LSTM basic layer for unbiased training
#corss-validation

!ls /content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids
!writefile .txt with ls result

!ls /content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids > /content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids_list.txt

file_path = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids_list.txt'

with open(file_path, 'r') as f:
    file_content = f.read()

print(file_content[:1000]) # Print the first 1000 characters to avoid flooding the output

import torch
import torch.nn as nn
import torch.nn.functional as F

class TransformerDiscriminator(nn.Module):
    def __init__(self, vocab_size, hidden_size, num_layers, num_heads, max_seq_length, condition_size=0, num_channels=2):
        super(TransformerDiscriminator, self).__init__()
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.max_seq_length = max_seq_length
        self.condition_size = condition_size
        self.num_channels = num_channels # Number of channels (e.g., input and output)

        # Embedding layer for tokens
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Positional Encoding (using learned embeddings)
        self.positional_embedding = nn.Embedding(max_seq_length, hidden_size)

        # Channel Embedding
        self.channel_embedding = nn.Embedding(num_channels, hidden_size)


        # If using conditioning, a linear layer to process it
        if self.condition_size > 0:
             self.condition_linear = nn.Linear(condition_size, hidden_size)


        # Transformer Encoder Layers
        encoder_layer = nn.TransformerEncoderLayer(d_model=hidden_size, nhead=num_heads, batch_first=True)
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Final linear layer to output a single score
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x, channel_indices, conditioning=None):
        # x is expected to be of shape (batch_size, sequence_length) - the grid sequence
        # channel_indices is expected to be of shape (batch_size, sequence_length) indicating the channel for each token
        # conditioning is expected to be of shape (batch_size, condition_size) or None

        # Embed tokens
        embedded_tokens = self.embedding(x) # shape: (batch_size, sequence_length, hidden_size)

        # Add positional embedding
        positions = torch.arange(0, x.size(1)).unsqueeze(0).repeat(x.size(0), 1).to(x.device)
        embedded_positions = self.positional_embedding(positions) # shape: (batch_size, sequence_length, hidden_size)

        # Embed channel information
        embedded_channels = self.channel_embedding(channel_indices) # shape: (batch_size, sequence_length, hidden_size)

        # Combine embeddings (summing is a common approach)
        embedded = embedded_tokens + embedded_positions + embedded_channels # shape: (batch_size, sequence_length, hidden_size)


        # Process conditioning and combine with embedded sequence (simple addition to the first token)
        if conditioning is not None:
            processed_condition = self.condition_linear(conditioning).unsqueeze(1) # shape: (batch_size, 1, hidden_size)
            # Simple approach: add to the first token's embedding
            embedded[:, 0, :] = embedded[:, 0, :] + processed_condition[:, 0, :]


        # Pass through Transformer Encoder
        output_sequence = self.transformer_encoder(embedded) # shape: (batch_size, sequence_length, hidden_size)

        # Pool the output sequence to get a single representation per sequence
        pooled_output = torch.mean(output_sequence, dim=1) # shape: (batch_size, hidden_size)

        # Pass through the final linear layer
        score = self.fc(pooled_output) # shape: (batch_size, 1)

        # Apply sigmoid activation to get a probability score
        probability = torch.sigmoid(score)

        return probability

# Example Usage (assuming parameters)
# vocab_size = 12 # 0-9 for colors, -1 for start, -2 for separator, 0 for padding
# hidden_size = 128
# num_layers = 3
# num_heads = 4
# max_seq_length = 1802
# condition_size = 50 # Example size for conditioning information
# num_channels = 2 # Example: 0 for input channel, 1 for output channel

# transformer_discriminator = TransformerDiscriminator(vocab_size, hidden_size, num_layers, num_heads, max_seq_length, condition_size=condition_size, num_channels=num_channels)
# print(transformer_discriminator)

# Example forward pass (assuming dummy data)
# dummy_sequence = torch.randint(0, vocab_size, (32, max_seq_length)) # Batch size 32, sequence length 1802
# # Create dummy channel indices (e.g., first half input channel 0, second half output channel 1)
# dummy_channel_indices = torch.zeros(32, max_seq_length, dtype=torch.long)
# # Assuming separator token is at index 901 (start token + 900 input pixels)
# separator_token_index = 901 # This would need to be dynamically determined based on actual input grid size
# dummy_channel_indices[:, separator_token_index+1:] = 1
#
# dummy_conditioning = torch.randn(32, condition_size)
# discrimination_score = transformer_discriminator(dummy_sequence, dummy_channel_indices, dummy_conditioning)
# print("\nShape of discrimination score:", discrimination_score.shape)

import torch
import torch.nn as nn
import torch.nn.functional as F
import math

# Helper function for Rotary Positional Embedding (RoPE)
# This is a simplified version; a full RoPE implementation might be more complex
def rotate_half(x):
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat((-x2, x1), dim=-1)

def apply_rope(x, freqs):
    # x: (batch_size, sequence_length, hidden_size)
    # freqs: (sequence_length, hidden_size)
    # Apply RoPE to the last dimension
    return (x * freqs.cos()) + (rotate_half(x) * freqs.sin())

class TransformerGenerator(nn.Module):
    def __init__(self, vocab_size, hidden_size, num_layers, num_heads, max_seq_length, noise_dim=100, condition_size=0):
        super(TransformerGenerator, self).__init__()
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.num_heads = num_heads
        self.max_seq_length = max_seq_length
        self.noise_dim = noise_dim
        self.condition_size = condition_size

        # Embedding layer
        self.embedding = nn.Embedding(vocab_size, hidden_size)

        # Positional Encoding (Simplified RoPE-like)
        # Generate frequencies for RoPE
        freqs = 1.0 / (10000 ** (torch.arange(0, hidden_size, 2).float() / hidden_size))
        self.register_buffer('freqs', freqs.repeat_interleave(2).unsqueeze(0)) # shape: (1, hidden_size)


        # Linear layer to process noise and conditioning
        input_linear_size = self.noise_dim + self.condition_size
        self.input_linear = nn.Linear(input_linear_size, hidden_size) # Project to hidden_size


        # Transformer Decoder Layers
        # Using PyTorch's TransformerDecoderLayer and TransformerDecoder
        decoder_layer = nn.TransformerDecoderLayer(d_model=hidden_size, nhead=num_heads, batch_first=True)
        self.transformer_decoder = nn.TransformerDecoder(decoder_layer, num_layers=num_layers)

        # Final linear layer to output vocabulary scores
        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x, noise, conditioning=None):
        # x is expected to be of shape (batch_size, sequence_length) - the input grid sequence
        # noise is expected to be of shape (batch_size, noise_dim)
        # conditioning is expected to be of shape (batch_size, condition_size) or None

        # Embed the input sequence
        embedded = self.embedding(x) # shape: (batch_size, sequence_length, hidden_size)

        # Apply Positional Encoding (RoPE)
        # Need to expand freqs to match sequence length
        freqs = self.freqs[:, :embedded.size(1), :] # shape: (1, sequence_length, hidden_size)
        embedded = apply_rope(embedded, freqs)

        # Process noise and conditioning and potentially use it as initial state or add to embeddings
        # For a Transformer Decoder, we often use a learned query token or cross-attention.
        # A simple way to incorporate noise/conditioning is to add it to the input embeddings
        # after processing it through a linear layer.
        processed_combined_input = self.input_linear(noise if conditioning is None else torch.cat((noise, conditioning), dim=1)) # shape: (batch_size, hidden_size)
        # Expand and add to embeddings (requires careful broadcasting or unsqueezing)
        # Let's try adding to the first token's embedding as a simple approach for now
        # embedded[:, 0, :] = embedded[:, 0, :] + processed_combined_input


        # For a standard Transformer Decoder, we often need a memory or target sequence
        # In an autoregressive setup, the input 'x' serves as both the target and part of the memory
        # We need a causal mask to prevent attending to future tokens in the output sequence portion
        # Assuming x contains [start_token, input_grid, separator_token, output_grid]
        # The causal mask should apply from the separator_token onwards.
        # This requires a more complex mask than a standard causal mask.
        # For simplicity in this initial structure, let's assume a standard causal mask for now.
        # A proper implementation for ARC would need a custom mask.
        seq_len = x.size(1)
        causal_mask = torch.triu(torch.ones(seq_len, seq_len) * float('-inf'), diagonal=1).to(x.device)


        # Pass through Transformer Decoder
        # TransformerDecoder expects target (embedded), memory (can be None if self-attention only)
        # and masks.
        # For autoregressive generation from an input sequence, the input sequence itself
        # acts as the target.
        # We might need a separate "memory" if we have an encoder part, but for a decoder-only Generator,
        # the input sequence is the primary information.

        # Let's use the embedded sequence as the target for the decoder
        output_sequence = self.transformer_decoder(embedded, memory=None, tgt_mask=causal_mask) # shape: (batch_size, sequence_length, hidden_size)


        # Final linear layer
        logits = self.fc(output_sequence) # shape: (batch_size, sequence_length, vocab_size)

        # Softmax to get probabilities (often done in the loss function for numerical stability)
        # probabilities = F.softmax(logits, dim=-1)

        return logits # Return logits for use with CrossEntropyLoss

# Example Usage (assuming parameters)
# vocab_size = 12 # 0-9 for colors, -1 for start, -2 for separator, 0 for padding
# hidden_size = 128
# num_layers = 3
# num_heads = 4
# max_seq_length = 1802
# noise_dim = 100
# condition_size = 50 # Example size for conditioning information

# transformer_generator = TransformerGenerator(vocab_size, hidden_size, num_layers, num_heads, max_seq_length, noise_dim=noise_dim, condition_size=condition_size)
# print(transformer_generator)

# Example forward pass (assuming dummy data)
# dummy_input_sequence = torch.randint(0, vocab_size, (32, max_seq_length)) # Batch size 32, sequence length 1802
# dummy_noise = torch.randn(32, noise_dim)
# dummy_conditioning = torch.randn(32, condition_size)
# generated_logits = transformer_generator(dummy_input_sequence, dummy_noise, dummy_conditioning)
# print("\nShape of generated logits:", generated_logits.shape)

import torch
import torch.nn as nn

class Generator(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers=3, noise_dim=100, condition_size=0):
        super(Generator, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.noise_dim = noise_dim
        self.condition_size = condition_size

        # Embedding layer for the input sequence (grid values and special tokens)
        self.embedding = nn.Embedding(input_size, hidden_size)

        # Linear layer to process the noise vector and potentially conditioning information
        # The input size to this layer will depend on how noise and conditioning are combined
        # A simple approach is to concatenate noise and conditioning and then pass through a linear layer
        input_linear_size = self.noise_dim + self.condition_size
        self.input_linear = nn.Linear(input_linear_size, hidden_size)


        # Stacked Bidirectional LSTM layer(s)
        # Input size is hidden_size (from embedding)
        # Output size of BiLSTM is 2 * hidden_size because it's bidirectional
        self.lstm = nn.LSTM(hidden_size, hidden_size, num_layers, batch_first=True, bidirectional=True)


        # Linear layer to output the sequence
        # The input size to the linear layer will be 2 * hidden_size due to BiLSTM
        self.fc = nn.Linear(hidden_size * 2, output_size) # output_size would be the vocabulary size again

    def forward(self, x, noise, conditioning=None):
        # x is expected to be of shape (batch_size, sequence_length) - the input grid sequence
        # noise is expected to be of shape (batch_size, noise_dim)
        # conditioning is expected to be of shape (batch_size, condition_size) or None

        # Embed the input sequence
        embedded = self.embedding(x) # shape: (batch_size, sequence_length, hidden_size)

        # Process noise and conditioning
        if conditioning is not None:
            combined_input = torch.cat((noise, conditioning), dim=1)
        else:
            combined_input = noise

        # Pass combined input through linear layer - this output could be used to initialize LSTM state
        # or be incorporated differently. For now, let's just process it.
        processed_combined_input = self.input_linear(combined_input) # shape: (batch_size, hidden_size)

        # Pass embedded sequence through LSTM
        # We can potentially use processed_combined_input to initialize the hidden state of the LSTM
        # h0 = processed_combined_input.unsqueeze(0).repeat(self.num_layers * 2, 1, 1) # *2 for bidirectional
        # c0 = torch.zeros(self.num_layers * 2, x.size(0), self.hidden_size).to(x.device) # *2 for bidirectional
        # out, _ = self.lstm(embedded, (h0, c0))

        # For simplicity, let's just pass the embedded sequence through LSTM
        out, _ = self.lstm(embedded) # shape: (batch_size, sequence_length, 2 * hidden_size)


        # Pass through the linear layer to get output predictions
        # We apply the linear layer to each time step
        out = self.fc(out) # shape: (batch_size, sequence_length, output_size)

        return out

# Example Usage (assuming a vocabulary size and hidden size)
# vocab_size = 12 # 0-9 for colors, -1 for start, -2 for separator, 0 for padding
# hidden_size = 128
# output_size = vocab_size
# noise_dim = 100
# condition_size = 50 # Example size for conditioning information

# generator = Generator(vocab_size, hidden_size, output_size, num_layers=3, noise_dim=noise_dim, condition_size=condition_size)
# print(generator)

# Example forward pass (assuming dummy data)
# dummy_input_sequence = torch.randint(0, vocab_size, (32, 1802)) # Batch size 32, sequence length 1802
# dummy_noise = torch.randn(32, noise_dim)
# dummy_conditioning = torch.randn(32, condition_size)
# generated_output = generator(dummy_input_sequence, dummy_noise, dummy_conditioning)
# print("\nShape of generated output:", generated_output.shape)

import torch
from torch.utils.data import Dataset, DataLoader

from sklearn.model_selection import train_test_split

import numpy as np

# Calculate the maximum sequence length
max_sequence_length = max(len(seq) for seq in processed_sequences)

print(f"The maximum sequence length is: {max_sequence_length}")

import json
import os

file_path = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids/f2191680-4c0b-45d0-a05c-458be12cfd39.json'

try:
    with open(file_path, 'r') as f:
        task_data = json.load(f)
    print(json.dumps(task_data, indent=4)) # Print the content with indentation for better readability
except FileNotFoundError:
    print(f"Error: File not found at {file_path}")
except json.JSONDecodeError:
    print(f"Error: Could not decode JSON from {file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

import json
import os
from tqdm.notebook import tqdm # Import tqdm

# Define the directory containing the JSON files
data_dir = '/content/drive/MyDrive/Google_AI_Studio/ARCAGI2025/data/GridTransitionDataset/training_transformed_unique_ids'

# Get a list of all JSON files in the directory
json_files = [f for f in os.listdir(data_dir) if f.endswith('.json')]

processed_sequences = []

# Define special tokens
start_token = -1 # Using -1 as a placeholder for a special token
separator_token = -2 # Using -2 as a placeholder for a special token

# Iterate through all JSON files with tqdm progress bar
for file_name in tqdm(json_files, desc="Processing JSON files"):
    file_path = os.path.join(data_dir, file_name)

    try:
        # Load the JSON data
        with open(file_path, 'r') as f:
            task_data = json.load(f)

        # Check for 'train' examples first
        if 'train' in task_data and task_data['train']:
            for example in task_data['train']:
                if 'input' in example and 'output' in example:
                    input_grid = example['input']
                    output_grid = example['output']

                    # Flatten the input and output grids
                    flattened_input = [item for sublist in input_grid for item in sublist]
                    flattened_output = [item for sublist in output_grid for item in sublist]

                    # Create a sequence
                    sequence = [start_token] + flattened_input + [separator_token] + flattened_output
                    processed_sequences.append(sequence)
                else:
                    # print(f"Skipping example in {file_name} due to missing input or output within 'train'.") # Suppress this for cleaner output during full run
                    pass
        # If no 'train' examples, check for 'input' and 'output' directly
        elif 'input' in task_data and 'output' in task_data:
            input_grid = task_data['input']
            output_grid = task_data['output']

            # Flatten the input and output grids
            flattened_input = [item for sublist in input_grid for item in sublist]
            flattened_output = [item for sublist in output_grid for item in sublist]

            # Create a sequence
            sequence = [start_token] + flattened_input + [separator_token] + flattened_output
            processed_sequences.append(sequence)
        else:
            # print(f"Skipping {file_name} as it contains no training examples or top-level input/output.") # Suppress this for cleaner output during full run
            pass

    except json.JSONDecodeError:
        # print(f"Skipping {file_name} due to JSON decoding error.") # Suppress this for cleaner output during full run
        pass
    except Exception as e:
        print(f"An error occurred while processing {file_name}: {e}")

# Now you have a list of processed sequences in processed_sequences
print(f"\nSuccessfully processed {len(processed_sequences)} sequences.")
# You can print a few processed sequences to inspect
# for i, seq in enumerate(processed_sequences[:5]):
#     print(f"Sequence {i+1}: {seq}")
# Define the padding token
padding_token = 0 # Using 0 as the padding token

# Pad the sequences to the maximum length
padded_sequences = [seq + [padding_token] * (max_sequence_length - len(seq)) for seq in processed_sequences]

print(f"Original number of sequences: {len(processed_sequences)}")
print(f"Number of padded sequences: {len(padded_sequences)}")
print(f"Length of the first padded sequence: {len(padded_sequences[0])}")
print(f"Length of the last padded sequence: {len(padded_sequences[-1])}")

# You can print a few padded sequences to inspect
# for i, seq in enumerate(padded_sequences[:5]):
#     print(f"Padded Sequence {i+1}: {seq[:20]}...") # Print only the first 20 elements for brevity
# Convert the list of padded sequences to a NumPy array
padded_sequences_array = np.array(padded_sequences, dtype=np.int64)

print(f"Shape of the padded sequences NumPy array: {padded_sequences_array.shape}")
print(f"Data type of the array: {padded_sequences_array.dtype}")
# You can print a small portion of the array to inspect
# print("First 5 padded sequences (NumPy array):")
# print(padded_sequences_array[:5, :20]) # Print first 5 sequences, first 20 elements

# Split the data into training and validation sets
# Using a common split ratio of 80% for training and 20% for validation
# You can adjust the test_size parameter based on your needs
train_data, val_data = train_test_split(padded_sequences_array, test_size=0.2, random_state=42) # Using a fixed random state for reproducibility

print(f"Shape of the training data: {train_data.shape}")
print(f"Shape of the validation data: {val_data.shape}")

# Convert NumPy arrays to PyTorch tensors
train_data_tensor = torch.from_numpy(train_data)
val_data_tensor = torch.from_numpy(val_data)

# Define a custom Dataset
class ARCGridDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

# Create Dataset objects
train_dataset = ARCGridDataset(train_data_tensor)
val_dataset = ARCGridDataset(val_data_tensor)

# Define batch size (you can adjust this)
batch_size = 32

# Create DataLoader objects
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

print(f"Number of batches in training DataLoader: {len(train_dataloader)}")
print(f"Number of batches in validation DataLoader: {len(val_dataloader)}")

# You can iterate through a batch to see the output
# for batch in train_dataloader:
#     print("Shape of a training batch:", batch.shape)
#     print("Data type of a training batch:", batch.dtype)
#     break # Print only one batch









# Commented out IPython magic to ensure Python compatibility.
# %pip install tqdm





